import json, re, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

VOCAB_PATH = "assets/data/vocabulary.json"

NEW_WORDS = [
    # --- Work / Career ---
    {"german": "die Fähigkeit", "article": "die", "english": "ability, skill, capability", "wordType": "noun", "plural": "die Fähigkeiten", "verbForms": {}, "theme": "work", "sentences": {"present": "Er hat viele Fähigkeiten.", "past": "Sie zeigte ihre Fähigkeit.", "future": "Diese Fähigkeit wird gefragt sein.", "usage1": "Welche Fähigkeiten hast du?", "usage2": "Sprachliche Fähigkeiten sind wichtig.", "usage3": "Er entwickelt neue Fähigkeiten."}},
    {"german": "die Weiterbildung", "article": "die", "english": "further training, professional development", "wordType": "noun", "plural": "die Weiterbildungen", "verbForms": {}, "theme": "work", "sentences": {"present": "Er macht eine Weiterbildung.", "past": "Sie absolvierte eine Weiterbildung.", "future": "Ich werde mich weiterbilden.", "usage1": "Weiterbildung ist wichtig.", "usage2": "Der Arbeitgeber zahlt die Weiterbildung.", "usage3": "Gibt es Weiterbildungsmöglichkeiten?"}},
    {"german": "das Vorstellungsgespräch", "article": "das", "english": "job interview", "wordType": "noun", "plural": "die Vorstellungsgespräche", "verbForms": {}, "theme": "work", "sentences": {"present": "Er hat morgen ein Vorstellungsgespräch.", "past": "Das Vorstellungsgespräch lief gut.", "future": "Ich werde ein Vorstellungsgespräch haben.", "usage1": "Wie bereitet man sich vor?", "usage2": "Das Vorstellungsgespräch war schwierig.", "usage3": "Hast du das Vorstellungsgespräch bestanden?"}},
    {"german": "der Lebenslauf", "article": "der", "english": "CV, résumé", "wordType": "noun", "plural": "die Lebensläufe", "verbForms": {}, "theme": "work", "sentences": {"present": "Er schreibt seinen Lebenslauf.", "past": "Sie schickte ihren Lebenslauf.", "future": "Du musst deinen Lebenslauf aktualisieren.", "usage1": "Bitte schick uns deinen Lebenslauf.", "usage2": "Ein guter Lebenslauf ist wichtig.", "usage3": "Hast du deinen Lebenslauf dabei?"}},
    {"german": "die Abteilung", "article": "die", "english": "department (in company)", "wordType": "noun", "plural": "die Abteilungen", "verbForms": {}, "theme": "work", "sentences": {"present": "Er arbeitet in der IT-Abteilung.", "past": "Sie wechselte die Abteilung.", "future": "Ich werde in eine neue Abteilung kommen.", "usage1": "In welcher Abteilung arbeitest du?", "usage2": "Die Abteilung hat 20 Mitarbeiter.", "usage3": "Er leitet die Marketingabteilung."}},
    {"german": "die Besprechung", "article": "die", "english": "meeting, discussion", "wordType": "noun", "plural": "die Besprechungen", "verbForms": {}, "theme": "work", "sentences": {"present": "Wir haben jetzt eine Besprechung.", "past": "Die Besprechung dauerte zwei Stunden.", "future": "Morgen ist eine Besprechung.", "usage1": "Ich bin in einer Besprechung.", "usage2": "Die Besprechung beginnt um 9.", "usage3": "Können wir eine Besprechung ansetzen?"}},
    {"german": "das Praktikum", "article": "das", "english": "internship, work placement", "wordType": "noun", "plural": "die Praktika", "verbForms": {}, "theme": "work", "sentences": {"present": "Er macht ein Praktikum.", "past": "Sie absolvierte ein Praktikum.", "future": "Ich werde ein Praktikum machen.", "usage1": "Das Praktikum dauert drei Monate.", "usage2": "Wo machst du dein Praktikum?", "usage3": "Das Praktikum ist unbezahlt."}},
    {"german": "die Kündigung", "article": "die", "english": "dismissal; notice (of termination)", "wordType": "noun", "plural": "die Kündigungen", "verbForms": {}, "theme": "work", "sentences": {"present": "Er bekam eine Kündigung.", "past": "Sie reichte ihre Kündigung ein.", "future": "Die Kündigung wird zugestellt.", "usage1": "Er hat eine Kündigung bekommen.", "usage2": "Die Kündigung war ein Schock.", "usage3": "Wie lang ist die Kündigungsfrist?"}},
    {"german": "der Kollege", "article": "der", "english": "colleague (male)", "wordType": "noun", "plural": "die Kollegen", "verbForms": {}, "theme": "work", "sentences": {"present": "Mein Kollege hilft mir.", "past": "Er traf seinen Kollegen.", "future": "Du wirst deine Kollegen kennenlernen.", "usage1": "Das sind meine Kollegen.", "usage2": "Ich bin mit dem Kollegen befreundet.", "usage3": "Die Kollegen sind nett."}},
    {"german": "die Kollegin", "article": "die", "english": "colleague (female)", "wordType": "noun", "plural": "die Kolleginnen", "verbForms": {}, "theme": "work", "sentences": {"present": "Meine Kollegin ist krank.", "past": "Sie half ihrer Kollegin.", "future": "Meine neue Kollegin kommt nächste Woche.", "usage1": "Das ist meine Kollegin Petra.", "usage2": "Die Kolleginnen sind sehr hilfreich.", "usage3": "Ich arbeite gern mit meiner Kollegin."}},

    # --- Housing / Daily Life ---
    {"german": "der Aufzug", "article": "der", "english": "elevator, lift", "wordType": "noun", "plural": "die Aufzüge", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Der Aufzug ist defekt.", "past": "Wir nahmen den Aufzug.", "future": "Der Aufzug wird repariert.", "usage1": "Gibt es einen Aufzug?", "usage2": "Der Aufzug fährt in den 5. Stock.", "usage3": "Ich nehme den Aufzug."}},
    {"german": "der Briefkasten", "article": "der", "english": "mailbox, letterbox", "wordType": "noun", "plural": "die Briefkästen", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Der Briefkasten ist voll.", "past": "Er leerte den Briefkasten.", "future": "Das Paket liegt im Briefkasten.", "usage1": "Wirf den Brief in den Briefkasten.", "usage2": "Der Briefkasten wird täglich geleert.", "usage3": "Hast du den Briefkasten gecheckt?"}},
    {"german": "der Keller", "article": "der", "english": "cellar, basement", "wordType": "noun", "plural": "die Keller", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Das Fahrrad steht im Keller.", "past": "Er holte den Wein aus dem Keller.", "future": "Wir lagern das im Keller.", "usage1": "Wir haben einen Keller.", "usage2": "Im Keller ist es kühl.", "usage3": "Das Haus hat einen großen Keller."}},
    {"german": "der Balkon", "article": "der", "english": "balcony", "wordType": "noun", "plural": "die Balkone", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Sie sitzt auf dem Balkon.", "past": "Er trocknete die Wäsche auf dem Balkon.", "future": "Ich werde auf dem Balkon frühstücken.", "usage1": "Haben Sie einen Balkon?", "usage2": "Der Balkon hat Meerblick.", "usage3": "Die Blumen stehen auf dem Balkon."}},
    {"german": "die Bettwäsche", "article": "die", "english": "bed linen, bedding", "wordType": "noun", "plural": "die Bettwäschen", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Sie wechselt die Bettwäsche.", "past": "Er wusch die Bettwäsche.", "future": "Ich werde die Bettwäsche wechseln.", "usage1": "Saubere Bettwäsche ist wichtig.", "usage2": "Die Bettwäsche muss gewaschen werden.", "usage3": "Neue Bettwäsche kaufen."}},
    {"german": "der Vorhang", "article": "der", "english": "curtain", "wordType": "noun", "plural": "die Vorhänge", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Er zieht den Vorhang zu.", "past": "Sie kaufte neue Vorhänge.", "future": "Ich werde die Vorhänge waschen.", "usage1": "Zieh den Vorhang zu!", "usage2": "Die Vorhänge blockieren das Licht.", "usage3": "Schöne Vorhänge für das Wohnzimmer."}},
    {"german": "die Einrichtung", "article": "die", "english": "furnishings, interior; facility, institution", "wordType": "noun", "plural": "die Einrichtungen", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Die Einrichtung ist modern.", "past": "Sie kauften neue Einrichtung.", "future": "Wir werden die Einrichtung ändern.", "usage1": "Die Einrichtung gefällt mir.", "usage2": "Eine öffentliche Einrichtung.", "usage3": "Wie ist die Einrichtung?"}},
    {"german": "die Hausordnung", "article": "die", "english": "house rules", "wordType": "noun", "plural": "die Hausordnungen", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Die Hausordnung muss eingehalten werden.", "past": "Er verstieß gegen die Hausordnung.", "future": "Bitte lesen Sie die Hausordnung.", "usage1": "Laut Hausordnung ist Lärm verboten.", "usage2": "Die Hausordnung hängt im Flur.", "usage3": "Was steht in der Hausordnung?"}},

    # --- Health ---
    {"german": "die Sprechstunde", "article": "die", "english": "consultation hour, office hours (doctor)", "wordType": "noun", "plural": "die Sprechstunden", "verbForms": {}, "theme": "health", "sentences": {"present": "Die Sprechstunde beginnt um 9.", "past": "Er kam in der Sprechstunde.", "future": "Die nächste Sprechstunde ist Dienstag.", "usage1": "Wann ist Sprechstunde?", "usage2": "Außerhalb der Sprechstunde.", "usage3": "Die Sprechstunde dauert 2 Stunden."}},
    {"german": "das Rezept", "article": "das", "english": "prescription; recipe", "wordType": "noun", "plural": "die Rezepte", "verbForms": {}, "theme": "health", "sentences": {"present": "Der Arzt schreibt ein Rezept.", "past": "Er bekam ein Rezept.", "future": "Du wirst ein Rezept brauchen.", "usage1": "Ich brauche ein Rezept.", "usage2": "Das gibt es nur auf Rezept.", "usage3": "Das ist ein altes Familienrezept."}},
    {"german": "der Notfall", "article": "der", "english": "emergency", "wordType": "noun", "plural": "die Notfälle", "verbForms": {}, "theme": "health", "sentences": {"present": "Das ist ein Notfall!", "past": "Im Notfall rief er an.", "future": "Im Notfall rufen Sie 112 an.", "usage1": "Das ist kein Notfall.", "usage2": "Was tut man im Notfall?", "usage3": "Der Notfall wurde gemeldet."}},
    {"german": "die Untersuchung", "article": "die", "english": "examination, investigation", "wordType": "noun", "plural": "die Untersuchungen", "verbForms": {}, "theme": "health", "sentences": {"present": "Die Untersuchung dauert 30 Minuten.", "past": "Die Untersuchung ergab nichts.", "future": "Die Untersuchung wird morgen stattfinden.", "usage1": "Er braucht eine Untersuchung.", "usage2": "Die Ergebnisse der Untersuchung.", "usage3": "Bitte kommen Sie zur Untersuchung."}},
    {"german": "das Symptom", "article": "das", "english": "symptom", "wordType": "noun", "plural": "die Symptome", "verbForms": {}, "theme": "health", "sentences": {"present": "Er hat Symptome einer Erkältung.", "past": "Die Symptome verschwanden.", "future": "Die Symptome werden besser.", "usage1": "Welche Symptome haben Sie?", "usage2": "Typische Symptome sind Husten.", "usage3": "Die Symptome sind ernst."}},
    {"german": "die Grippe", "article": "die", "english": "flu, influenza", "wordType": "noun", "plural": "die Grippen", "verbForms": {}, "theme": "health", "sentences": {"present": "Er hat die Grippe.", "past": "Sie lag wochenlang mit Grippe im Bett.", "future": "Ich werde mich gegen Grippe impfen.", "usage1": "Ich habe die Grippe.", "usage2": "Grippe ist ansteckend.", "usage3": "Die Grippesaison beginnt im Herbst."}},
    {"german": "die Allergie", "article": "die", "english": "allergy", "wordType": "noun", "plural": "die Allergien", "verbForms": {}, "theme": "health", "sentences": {"present": "Er hat eine Allergie gegen Pollen.", "past": "Die Allergie wurde festgestellt.", "future": "Die Allergie wird behandelt.", "usage1": "Ich habe eine Allergie.", "usage2": "Haben Sie Allergien?", "usage3": "Eine schwere Allergie."}},
    {"german": "die Versicherung", "article": "die", "english": "insurance", "wordType": "noun", "plural": "die Versicherungen", "verbForms": {}, "theme": "health", "sentences": {"present": "Er hat eine Krankenversicherung.", "past": "Sie schloss eine Versicherung ab.", "future": "Du brauchst eine Versicherung.", "usage1": "Welche Versicherung haben Sie?", "usage2": "Die Versicherung zahlt das.", "usage3": "Eine Versicherung abschließen."}},

    # --- Transport / Travel ---
    {"german": "die Verspätung", "article": "die", "english": "delay, lateness", "wordType": "noun", "plural": "die Verspätungen", "verbForms": {}, "theme": "travel", "sentences": {"present": "Der Zug hat Verspätung.", "past": "Der Flug hatte 2 Stunden Verspätung.", "future": "Es wird Verspätungen geben.", "usage1": "Entschuldigung für die Verspätung.", "usage2": "Der Bus hatte keine Verspätung.", "usage3": "Mit Verspätung ankommen."}},
    {"german": "die Abfahrt", "article": "die", "english": "departure (transport)", "wordType": "noun", "plural": "die Abfahrten", "verbForms": {}, "theme": "travel", "sentences": {"present": "Die Abfahrt ist um 10 Uhr.", "past": "Die Abfahrt erfolgte pünktlich.", "future": "Wann ist die nächste Abfahrt?", "usage1": "Die Abfahrt steht auf dem Plan.", "usage2": "Pünktliche Abfahrt.", "usage3": "Wann ist Abfahrt?"}},
    {"german": "die Ankunft", "article": "die", "english": "arrival", "wordType": "noun", "plural": "die Ankünfte", "verbForms": {}, "theme": "travel", "sentences": {"present": "Die Ankunft ist um 15 Uhr.", "past": "Bei seiner Ankunft warteten alle.", "future": "Die Ankunft des Zuges.", "usage1": "Wann ist die Ankunft?", "usage2": "Ankunft: 16:45.", "usage3": "Die Ankunft verzögerte sich."}},
    {"german": "der Fahrplan", "article": "der", "english": "timetable, schedule", "wordType": "noun", "plural": "die Fahrpläne", "verbForms": {}, "theme": "travel", "sentences": {"present": "Er schaut in den Fahrplan.", "past": "Sie las den Fahrplan.", "future": "Der Fahrplan ändert sich.", "usage1": "Wo ist der Fahrplan?", "usage2": "Laut Fahrplan kommt der Bus um 8.", "usage3": "Den Fahrplan online prüfen."}},
    {"german": "der Stau", "article": "der", "english": "traffic jam", "wordType": "noun", "plural": "die Staus", "verbForms": {}, "theme": "travel", "sentences": {"present": "Auf der Autobahn ist Stau.", "past": "Er steckte im Stau.", "future": "Es wird Stau geben.", "usage1": "Ich bin im Stau.", "usage2": "Wegen Stau bin ich spät.", "usage3": "Jeden Morgen Stau auf der A1."}},
    {"german": "die Umleitung", "article": "die", "english": "diversion, detour", "wordType": "noun", "plural": "die Umleitungen", "verbForms": {}, "theme": "travel", "sentences": {"present": "Es gibt eine Umleitung.", "past": "Die Umleitung war lang.", "future": "Die Umleitung wird aufgehoben.", "usage1": "Bitte folgen Sie der Umleitung.", "usage2": "Die Umleitung führt durch die Stadt.", "usage3": "Wegen Baustelle gibt es eine Umleitung."}},
    {"german": "die Linie", "article": "die", "english": "line (bus/tram/metro)", "wordType": "noun", "plural": "die Linien", "verbForms": {}, "theme": "travel", "sentences": {"present": "Die Linie 3 fährt zum Bahnhof.", "past": "Er fuhr mit Linie 5.", "future": "Welche Linie nehmen wir?", "usage1": "Welche Linie fährt ins Zentrum?", "usage2": "Die U-Bahn Linie 2.", "usage3": "Die Linie ist direkt."}},
    {"german": "der Führerschein", "article": "der", "english": "driving licence", "wordType": "noun", "plural": "die Führerscheine", "verbForms": {}, "theme": "travel", "sentences": {"present": "Er macht den Führerschein.", "past": "Sie bekam ihren Führerschein.", "future": "Ich werde den Führerschein machen.", "usage1": "Hast du einen Führerschein?", "usage2": "Den Führerschein zeigen.", "usage3": "Der Führerschein ist abgelaufen."}},

    # --- Media / Information ---
    {"german": "die Sendung", "article": "die", "english": "broadcast, programme; shipment", "wordType": "noun", "plural": "die Sendungen", "verbForms": {}, "theme": "technology", "sentences": {"present": "Die Sendung beginnt um 20 Uhr.", "past": "Er verpasste die Sendung.", "future": "Die Sendung wird aufgenommen.", "usage1": "Welche Sendung läuft gerade?", "usage2": "Eine interessante Sendung.", "usage3": "Die Sendung wurde wiederholt."}},
    {"german": "das Programm", "article": "das", "english": "programme, schedule; software program", "wordType": "noun", "plural": "die Programme", "verbForms": {}, "theme": "technology", "sentences": {"present": "Das Programm läuft bis 22 Uhr.", "past": "Er öffnete das Programm.", "future": "Das Programm wird aktualisiert.", "usage1": "Was steht im Programm?", "usage2": "Das Programm installieren.", "usage3": "Das Programm ist abgestürzt."}},
    {"german": "der Kanal", "article": "der", "english": "channel (TV); canal", "wordType": "noun", "plural": "die Kanäle", "verbForms": {}, "theme": "technology", "sentences": {"present": "Er wechselt den Kanal.", "past": "Sie schaute einen anderen Kanal.", "future": "Den Kanal wechseln.", "usage1": "Auf welchem Kanal läuft das?", "usage2": "Der Kanal 3 zeigt das.", "usage3": "Einen YouTube-Kanal abonnieren."}},
    {"german": "die Werbung", "article": "die", "english": "advertising, advertisement", "wordType": "noun", "plural": "die Werbungen", "verbForms": {}, "theme": "technology", "sentences": {"present": "Im Fernsehen läuft viel Werbung.", "past": "Die Werbung war kreativ.", "future": "Es wird neue Werbung geben.", "usage1": "Ich mag keine Werbung.", "usage2": "Werbung im Internet.", "usage3": "Die Werbung kostet viel Geld."}},
    {"german": "der Bericht", "article": "der", "english": "report", "wordType": "noun", "plural": "die Berichte", "verbForms": {}, "theme": "society", "sentences": {"present": "Der Bericht ist fertig.", "past": "Sie schrieb einen Bericht.", "future": "Ich werde einen Bericht schreiben.", "usage1": "Laut Bericht ist alles gut.", "usage2": "Ein Bericht über das Klima.", "usage3": "Den Bericht lesen."}},
    {"german": "die Zeitschrift", "article": "die", "english": "magazine, journal", "wordType": "noun", "plural": "die Zeitschriften", "verbForms": {}, "theme": "education", "sentences": {"present": "Er liest eine Zeitschrift.", "past": "Sie abonnierte die Zeitschrift.", "future": "Ich werde die Zeitschrift kaufen.", "usage1": "Eine monatliche Zeitschrift.", "usage2": "Welche Zeitschrift liest du?", "usage3": "Eine wissenschaftliche Zeitschrift."}},

    # --- Society / Politics ---
    {"german": "die Demokratie", "article": "die", "english": "democracy", "wordType": "noun", "plural": "die Demokratien", "verbForms": {}, "theme": "society", "sentences": {"present": "Deutschland ist eine Demokratie.", "past": "Die Demokratie wurde eingeführt.", "future": "Die Demokratie muss geschützt werden.", "usage1": "In einer Demokratie wählen die Bürger.", "usage2": "Demokratie bedeutet Freiheit.", "usage3": "Für die Demokratie eintreten."}},
    {"german": "die Partei", "article": "die", "english": "political party", "wordType": "noun", "plural": "die Parteien", "verbForms": {}, "theme": "society", "sentences": {"present": "Er ist Mitglied einer Partei.", "past": "Die Partei gewann die Wahl.", "future": "Die Parteien werden debattieren.", "usage1": "Welche Partei wählst du?", "usage2": "Die Partei hat viele Mitglieder.", "usage3": "Eine neue Partei gründen."}},
    {"german": "die Steuer", "article": "die", "english": "tax", "wordType": "noun", "plural": "die Steuern", "verbForms": {}, "theme": "society", "sentences": {"present": "Er zahlt hohe Steuern.", "past": "Die Steuern wurden erhöht.", "future": "Die Steuer wird gesenkt.", "usage1": "Steuern zahlen.", "usage2": "Die Einkommensteuer.", "usage3": "Steuern sind Pflicht."}},
    {"german": "die Pflicht", "article": "die", "english": "duty, obligation", "wordType": "noun", "plural": "die Pflichten", "verbForms": {}, "theme": "society", "sentences": {"present": "Es ist seine Pflicht.", "past": "Sie erfüllte ihre Pflicht.", "future": "Das ist eine Pflicht.", "usage1": "Rechte und Pflichten.", "usage2": "Das ist meine Pflicht.", "usage3": "Pflichten im Alltag."}},
    {"german": "die Verantwortung", "article": "die", "english": "responsibility", "wordType": "noun", "plural": "die Verantwortungen", "verbForms": {}, "theme": "society", "sentences": {"present": "Er trägt die Verantwortung.", "past": "Sie übernahm die Verantwortung.", "future": "Das ist deine Verantwortung.", "usage1": "Verantwortung übernehmen.", "usage2": "Er fühlt sich verantwortlich.", "usage3": "Keine Verantwortung ablehnen."}},
    {"german": "der Bürger", "article": "der", "english": "citizen", "wordType": "noun", "plural": "die Bürger", "verbForms": {}, "theme": "society", "sentences": {"present": "Die Bürger wählen den Präsidenten.", "past": "Die Bürger protestierten.", "future": "Die Bürger werden befragt.", "usage1": "Ein Bürger hat Rechte.", "usage2": "Die Bürger der Stadt.", "usage3": "Als Bürger hast du Pflichten."}},
    {"german": "das Recht", "article": "das", "english": "right; law", "wordType": "noun", "plural": "die Rechte", "verbForms": {}, "theme": "society", "sentences": {"present": "Er hat das Recht zu wählen.", "past": "Das Recht wurde eingeführt.", "future": "Deine Rechte werden geschützt.", "usage1": "Jeder hat Rechte.", "usage2": "Das ist mein Recht.", "usage3": "Rechte und Pflichten."}},

    # --- Nature / Environment ---
    {"german": "die Überschwemmung", "article": "die", "english": "flood, flooding", "wordType": "noun", "plural": "die Überschwemmungen", "verbForms": {}, "theme": "environment", "sentences": {"present": "Die Überschwemmung ist schlimm.", "past": "Die Überschwemmung zerstörte Häuser.", "future": "Überschwemmungen werden häufiger.", "usage1": "Nach der Überschwemmung.", "usage2": "Die Überschwemmung kam plötzlich.", "usage3": "Schutz vor Überschwemmungen."}},
    {"german": "die Dürre", "article": "die", "english": "drought", "wordType": "noun", "plural": "die Dürren", "verbForms": {}, "theme": "environment", "sentences": {"present": "Die Dürre schadet der Ernte.", "past": "Die Dürre dauerte Monate.", "future": "Dürren werden durch den Klimawandel häufiger.", "usage1": "Eine lange Dürre.", "usage2": "Die Dürre zerstört die Felder.", "usage3": "Wasserknappheit durch Dürre."}},
    {"german": "das Gewässer", "article": "das", "english": "body of water, waterway", "wordType": "noun", "plural": "die Gewässer", "verbForms": {}, "theme": "environment", "sentences": {"present": "Das Gewässer ist sauber.", "past": "Die Gewässer wurden verschmutzt.", "future": "Wir müssen die Gewässer schützen.", "usage1": "Ein natürliches Gewässer.", "usage2": "Die Gewässer reinigen.", "usage3": "Saubere Gewässer sind wichtig."}},
    {"german": "der Müll", "article": "der", "english": "rubbish, garbage, waste", "wordType": "noun", "plural": "", "verbForms": {}, "theme": "environment", "sentences": {"present": "Er wirft den Müll weg.", "past": "Der Müll wurde getrennt.", "future": "Wir müssen weniger Müll produzieren.", "usage1": "Müll trennen ist wichtig.", "usage2": "Den Müll rausbringen.", "usage3": "Illegale Müllentsorgung ist verboten."}},
    {"german": "die Energie", "article": "die", "english": "energy", "wordType": "noun", "plural": "die Energien", "verbForms": {}, "theme": "environment", "sentences": {"present": "Wir brauchen saubere Energie.", "past": "Die Energie wurde gespart.", "future": "Erneuerbare Energie wird wichtiger.", "usage1": "Energie sparen.", "usage2": "Die Energiekosten steigen.", "usage3": "Solarenergie ist nachhaltig."}},

    # --- Shopping / Finance ---
    {"german": "die Quittung", "article": "die", "english": "receipt", "wordType": "noun", "plural": "die Quittungen", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Er braucht die Quittung.", "past": "Sie hob die Quittung auf.", "future": "Ich werde die Quittung aufheben.", "usage1": "Kann ich eine Quittung haben?", "usage2": "Die Quittung ist wichtig.", "usage3": "Ohne Quittung kein Umtausch."}},
    {"german": "der Rabatt", "article": "der", "english": "discount", "wordType": "noun", "plural": "die Rabatte", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Er bekommt 10% Rabatt.", "past": "Sie bekam einen Rabatt.", "future": "Gibt es Rabatt?", "usage1": "Mit Studentenrabatt.", "usage2": "Einen Rabatt bekommen.", "usage3": "20% Rabatt auf alles."}},
    {"german": "das Konto", "article": "das", "english": "bank account", "wordType": "noun", "plural": "die Konten", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Er eröffnet ein Konto.", "past": "Sie hat ihr Konto gesperrt.", "future": "Ich werde ein Konto eröffnen.", "usage1": "Auf mein Konto überweisen.", "usage2": "Das Konto ist leer.", "usage3": "Ein Konto bei der Sparkasse."}},
    {"german": "der Betrag", "article": "der", "english": "amount, sum (of money)", "wordType": "noun", "plural": "die Beträge", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Der Betrag ist zu hoch.", "past": "Der Betrag wurde überwiesen.", "future": "Den Betrag zahlen.", "usage1": "Welchen Betrag soll ich zahlen?", "usage2": "Ein kleiner Betrag.", "usage3": "Der Betrag ist fällig."}},
    {"german": "das Sonderangebot", "article": "das", "english": "special offer", "wordType": "noun", "plural": "die Sonderangebote", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Das ist im Sonderangebot.", "past": "Das Sonderangebot lief eine Woche.", "future": "Nächste Woche gibt es Sonderangebote.", "usage1": "Im Sonderangebot kaufen.", "usage2": "Das Sonderangebot gilt bis Sonntag.", "usage3": "Sonderangebote im Supermarkt."}},

    # --- Education ---
    {"german": "das Zeugnis", "article": "das", "english": "report card; certificate; testimony", "wordType": "noun", "plural": "die Zeugnisse", "verbForms": {}, "theme": "education", "sentences": {"present": "Er bekommt sein Zeugnis.", "past": "Sie hatte ein gutes Zeugnis.", "future": "Das Zeugnis wird ausgestellt.", "usage1": "Gutes Zeugnis bekommen.", "usage2": "Ein Zeugnis vorlegen.", "usage3": "Das Schulzeugnis ist wichtig."}},
    {"german": "die Bildung", "article": "die", "english": "education; formation", "wordType": "noun", "plural": "", "verbForms": {}, "theme": "education", "sentences": {"present": "Bildung ist wichtig.", "past": "Sie investierte in ihre Bildung.", "future": "Bildung wird immer wichtiger.", "usage1": "Gute Bildung ermöglicht vieles.", "usage2": "Das Bildungssystem.", "usage3": "Bildung ist ein Grundrecht."}},
    {"german": "die Aufgabe", "article": "die", "english": "task, exercise; duty", "wordType": "noun", "plural": "die Aufgaben", "verbForms": {}, "theme": "education", "sentences": {"present": "Er macht seine Aufgaben.", "past": "Sie erledigte alle Aufgaben.", "future": "Ich werde die Aufgaben machen.", "usage1": "Eine schwere Aufgabe.", "usage2": "Aufgaben für zu Hause.", "usage3": "Das ist keine leichte Aufgabe."}},
    {"german": "der Unterricht", "article": "der", "english": "lesson, class, instruction", "wordType": "noun", "plural": "die Unterrichte", "verbForms": {}, "theme": "education", "sentences": {"present": "Der Unterricht beginnt um 8.", "past": "Der Unterricht fiel aus.", "future": "Der Unterricht wird stattfinden.", "usage1": "Im Unterricht aufpassen.", "usage2": "Guter Unterricht ist wichtig.", "usage3": "Den Unterricht versäumen."}},
    {"german": "die Erfahrung", "article": "die", "english": "experience", "wordType": "noun", "plural": "die Erfahrungen", "verbForms": {}, "theme": "work", "sentences": {"present": "Er hat viel Erfahrung.", "past": "Das war eine wichtige Erfahrung.", "future": "Du wirst Erfahrungen sammeln.", "usage1": "Berufliche Erfahrung.", "usage2": "Erfahrungen machen.", "usage3": "Das ist eine neue Erfahrung."}},

    # --- Culture / Leisure ---
    {"german": "die Ausstellung", "article": "die", "english": "exhibition, display", "wordType": "noun", "plural": "die Ausstellungen", "verbForms": {}, "theme": "culture", "sentences": {"present": "Die Ausstellung ist sehenswert.", "past": "Sie besuchten die Ausstellung.", "future": "Die Ausstellung wird eröffnet.", "usage1": "Eine Kunstausstellung.", "usage2": "Die Ausstellung dauert bis Ende Mai.", "usage3": "Wann öffnet die Ausstellung?"}},
    {"german": "die Veranstaltung", "article": "die", "english": "event, function", "wordType": "noun", "plural": "die Veranstaltungen", "verbForms": {}, "theme": "culture", "sentences": {"present": "Die Veranstaltung beginnt um 19 Uhr.", "past": "Die Veranstaltung war gut besucht.", "future": "Die Veranstaltung wird organisiert.", "usage1": "Eine kulturelle Veranstaltung.", "usage2": "Die Veranstaltung ist ausverkauft.", "usage3": "Welche Veranstaltungen gibt es?"}},
    {"german": "die Eintrittskarte", "article": "die", "english": "admission ticket, entry ticket", "wordType": "noun", "plural": "die Eintrittskarten", "verbForms": {}, "theme": "culture", "sentences": {"present": "Er kauft die Eintrittskarte.", "past": "Sie reservierte die Eintrittskarten.", "future": "Ich werde die Karte kaufen.", "usage1": "Wo kauft man Eintrittskarten?", "usage2": "Die Eintrittskarte kostet 15 Euro.", "usage3": "Mit Eintrittskarte eintreten."}},
    {"german": "der Ausflug", "article": "der", "english": "excursion, day trip", "wordType": "noun", "plural": "die Ausflüge", "verbForms": {}, "theme": "travel", "sentences": {"present": "Wir machen einen Ausflug.", "past": "Der Ausflug war toll.", "future": "Wir werden einen Ausflug machen.", "usage1": "Ein Ausflug in die Natur.", "usage2": "Schulausflug ins Museum.", "usage3": "Wohin soll der Ausflug gehen?"}},
    {"german": "die Unterkunft", "article": "die", "english": "accommodation, lodging", "wordType": "noun", "plural": "die Unterkünfte", "verbForms": {}, "theme": "travel", "sentences": {"present": "Die Unterkunft ist günstig.", "past": "Sie suchten eine Unterkunft.", "future": "Wir brauchen eine Unterkunft.", "usage1": "Welche Unterkunft habt ihr?", "usage2": "Die Unterkunft ist zentral gelegen.", "usage3": "Eine Unterkunft buchen."}},
    {"german": "der Urlaub", "article": "der", "english": "holiday, vacation", "wordType": "noun", "plural": "die Urlaube", "verbForms": {}, "theme": "travel", "sentences": {"present": "Er macht Urlaub.", "past": "Sie war im Urlaub in Spanien.", "future": "Wir werden Urlaub machen.", "usage1": "Schönen Urlaub!", "usage2": "Wo machst du Urlaub?", "usage3": "Urlaub planen."}},

    # --- Relationships / People ---
    {"german": "der Bekannte", "article": "der", "english": "acquaintance (male)", "wordType": "noun", "plural": "die Bekannten", "verbForms": {}, "theme": "relationships", "sentences": {"present": "Er ist ein Bekannter von mir.", "past": "Sie traf einen alten Bekannten.", "future": "Ich werde ihn als Bekannten vorstellen.", "usage1": "Das ist ein Bekannter.", "usage2": "Er ist mehr als ein Bekannter.", "usage3": "Einen Bekannten treffen."}},
    {"german": "die Beziehung", "article": "die", "english": "relationship; connection", "wordType": "noun", "plural": "die Beziehungen", "verbForms": {}, "theme": "relationships", "sentences": {"present": "Sie haben eine gute Beziehung.", "past": "Die Beziehung endete.", "future": "Wir werden eine gute Beziehung aufbauen.", "usage1": "Eine enge Beziehung.", "usage2": "Die Beziehung ist schwierig.", "usage3": "Gute Beziehungen pflegen."}},
    {"german": "das Vertrauen", "article": "das", "english": "trust, confidence", "wordType": "noun", "plural": "", "verbForms": {}, "theme": "relationships", "sentences": {"present": "Sie hat großes Vertrauen in ihn.", "past": "Er hatte ihr Vertrauen.", "future": "Das Vertrauen wird wachsen.", "usage1": "Vertrauen ist wichtig.", "usage2": "Das Vertrauen wurde zerstört.", "usage3": "Vertrauen aufbauen."}},
    {"german": "der Konflikt", "article": "der", "english": "conflict", "wordType": "noun", "plural": "die Konflikte", "verbForms": {}, "theme": "relationships", "sentences": {"present": "Es gibt einen Konflikt.", "past": "Der Konflikt wurde gelöst.", "future": "Der Konflikt wird eskalieren.", "usage1": "Einen Konflikt lösen.", "usage2": "Im Konflikt sein.", "usage3": "Konflikte vermeiden."}},

    # --- Language / Communication ---
    {"german": "die Übersetzung", "article": "die", "english": "translation", "wordType": "noun", "plural": "die Übersetzungen", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Die Übersetzung ist fertig.", "past": "Sie machte die Übersetzung.", "future": "Ich werde die Übersetzung prüfen.", "usage1": "Eine gute Übersetzung.", "usage2": "Die Übersetzung ist schwierig.", "usage3": "Die Übersetzung des Textes."}},
    {"german": "der Ausdruck", "article": "der", "english": "expression; printout", "wordType": "noun", "plural": "die Ausdrücke", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Das ist ein interessanter Ausdruck.", "past": "Sie benutzte den falschen Ausdruck.", "future": "Lern diesen Ausdruck.", "usage1": "Typischer Ausdruck auf Deutsch.", "usage2": "Einen Ausdruck machen.", "usage3": "Welchen Ausdruck verwendet man?"}},
    {"german": "der Satz", "article": "der", "english": "sentence; set; leap", "wordType": "noun", "plural": "die Sätze", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Bilde einen Satz.", "past": "Der Satz war falsch.", "future": "Schreib fünf Sätze.", "usage1": "Ein vollständiger Satz.", "usage2": "Den Satz übersetzen.", "usage3": "Richtige Sätze bilden."}},
    {"german": "der Wortschatz", "article": "der", "english": "vocabulary, word stock", "wordType": "noun", "plural": "die Wortschätze", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Er hat einen großen Wortschatz.", "past": "Sie erweiterte ihren Wortschatz.", "future": "Ich werde meinen Wortschatz verbessern.", "usage1": "Den Wortschatz üben.", "usage2": "Ein reicher Wortschatz.", "usage3": "Wortschatz für die Prüfung."}},
    {"german": "die Grammatik", "article": "die", "english": "grammar", "wordType": "noun", "plural": "die Grammatiken", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Die Grammatik ist schwierig.", "past": "Er lernte die Grammatik.", "future": "Grammatik üben.", "usage1": "Deutsche Grammatik.", "usage2": "Grammatikfehler machen.", "usage3": "Die Grammatik verstehen."}},

    # --- General / Other ---
    {"german": "der Grund", "article": "der", "english": "reason; ground, floor", "wordType": "noun", "plural": "die Gründe", "verbForms": {}, "theme": "other", "sentences": {"present": "Was ist der Grund?", "past": "Er nannte keinen Grund.", "future": "Es wird einen Grund geben.", "usage1": "Aus diesem Grund.", "usage2": "Der Grund ist unklar.", "usage3": "Ohne Grund."}},
    {"german": "der Unterschied", "article": "der", "english": "difference", "wordType": "noun", "plural": "die Unterschiede", "verbForms": {}, "theme": "other", "sentences": {"present": "Es gibt einen Unterschied.", "past": "Der Unterschied war groß.", "future": "Der Unterschied wird kleiner.", "usage1": "Was ist der Unterschied?", "usage2": "Ein großer Unterschied.", "usage3": "Den Unterschied erkennen."}},
    {"german": "die Möglichkeit", "article": "die", "english": "possibility, opportunity", "wordType": "noun", "plural": "die Möglichkeiten", "verbForms": {}, "theme": "other", "sentences": {"present": "Es gibt viele Möglichkeiten.", "past": "Er nutzte die Möglichkeit.", "future": "Es wird eine Möglichkeit geben.", "usage1": "Gibt es eine Möglichkeit?", "usage2": "Alle Möglichkeiten prüfen.", "usage3": "Eine gute Möglichkeit."}},
    {"german": "der Vorteil", "article": "der", "english": "advantage", "wordType": "noun", "plural": "die Vorteile", "verbForms": {}, "theme": "other", "sentences": {"present": "Das hat viele Vorteile.", "past": "Er nutzte den Vorteil.", "future": "Das wird Vorteile bringen.", "usage1": "Vor- und Nachteile.", "usage2": "Das ist ein großer Vorteil.", "usage3": "Den Vorteil nutzen."}},
    {"german": "der Nachteil", "article": "der", "english": "disadvantage", "wordType": "noun", "plural": "die Nachteile", "verbForms": {}, "theme": "other", "sentences": {"present": "Das hat Nachteile.", "past": "Der Nachteil war klar.", "future": "Das wird Nachteile haben.", "usage1": "Ein Nachteil davon.", "usage2": "Vor- und Nachteile abwägen.", "usage3": "Kein wesentlicher Nachteil."}},
    {"german": "der Fehler", "article": "der", "english": "mistake, error", "wordType": "noun", "plural": "die Fehler", "verbForms": {}, "theme": "other", "sentences": {"present": "Er macht Fehler.", "past": "Sie korrigierte den Fehler.", "future": "Fehler passieren.", "usage1": "Das war ein Fehler.", "usage2": "Einen Fehler machen.", "usage3": "Fehler sind menschlich."}},
    {"german": "die Lösung", "article": "die", "english": "solution", "wordType": "noun", "plural": "die Lösungen", "verbForms": {}, "theme": "other", "sentences": {"present": "Er findet eine Lösung.", "past": "Die Lösung wurde gefunden.", "future": "Wir werden eine Lösung finden.", "usage1": "Gibt es eine Lösung?", "usage2": "Eine einfache Lösung.", "usage3": "Die Lösung des Problems."}},
    {"german": "das Ergebnis", "article": "das", "english": "result, outcome", "wordType": "noun", "plural": "die Ergebnisse", "verbForms": {}, "theme": "other", "sentences": {"present": "Das Ergebnis ist positiv.", "past": "Das Ergebnis überraschte uns.", "future": "Das Ergebnis wird bekannt.", "usage1": "Welches Ergebnis?", "usage2": "Ein gutes Ergebnis.", "usage3": "Das Ergebnis abwarten."}},
    {"german": "die Entscheidung", "article": "die", "english": "decision", "wordType": "noun", "plural": "die Entscheidungen", "verbForms": {}, "theme": "other", "sentences": {"present": "Er trifft eine Entscheidung.", "past": "Die Entscheidung war schwer.", "future": "Ich werde die Entscheidung treffen.", "usage1": "Eine wichtige Entscheidung.", "usage2": "Die Entscheidung liegt bei dir.", "usage3": "Eine Entscheidung treffen."}},
    {"german": "die Bedeutung", "article": "die", "english": "meaning; significance", "wordType": "noun", "plural": "die Bedeutungen", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Was ist die Bedeutung dieses Wortes?", "past": "Die Bedeutung war unklar.", "future": "Die Bedeutung wird klar.", "usage1": "Was hat das für eine Bedeutung?", "usage2": "Ein Wort mit vielen Bedeutungen.", "usage3": "Die Bedeutung verstehen."}},
    {"german": "die Wirkung", "article": "die", "english": "effect, impact", "wordType": "noun", "plural": "die Wirkungen", "verbForms": {}, "theme": "health", "sentences": {"present": "Das Medikament zeigt Wirkung.", "past": "Die Wirkung war stark.", "future": "Die Wirkung wird nachlassen.", "usage1": "Welche Wirkung hat das?", "usage2": "Eine positive Wirkung.", "usage3": "Die Wirkung eines Medikaments."}},
    {"german": "das Ziel", "article": "das", "english": "goal, target, destination", "wordType": "noun", "plural": "die Ziele", "verbForms": {}, "theme": "work", "sentences": {"present": "Er erreicht sein Ziel.", "past": "Das Ziel wurde erreicht.", "future": "Ich werde mein Ziel erreichen.", "usage1": "Was ist dein Ziel?", "usage2": "Ein Ziel setzen.", "usage3": "Das Ziel vor Augen haben."}},
    {"german": "das Erlebnis", "article": "das", "english": "experience, adventure", "wordType": "noun", "plural": "die Erlebnisse", "verbForms": {}, "theme": "travel", "sentences": {"present": "Das ist ein tolles Erlebnis.", "past": "Sie hatten viele Erlebnisse.", "future": "Das wird ein unvergessliches Erlebnis sein.", "usage1": "Ein besonderes Erlebnis.", "usage2": "Erlebnisse sammeln.", "usage3": "Was für ein Erlebnis!"}},
    {"german": "die Gelegenheit", "article": "die", "english": "opportunity, occasion", "wordType": "noun", "plural": "die Gelegenheiten", "verbForms": {}, "theme": "other", "sentences": {"present": "Das ist eine gute Gelegenheit.", "past": "Er nutzte die Gelegenheit.", "future": "Die Gelegenheit kommt wieder.", "usage1": "Bei dieser Gelegenheit.", "usage2": "Eine seltene Gelegenheit.", "usage3": "Die Gelegenheit nicht verpassen."}},
]

with open(VOCAB_PATH, encoding='utf-8') as f:
    vocab = json.load(f)

our_lower = {w['german'].lower() for w in vocab}
max_idx = max(int(w['id'].split('_')[-1]) for w in vocab if w['id'].split('_')[-1].isdigit())
idx = max_idx + 1

added, skipped = [], []
for w in NEW_WORDS:
    if w['german'].lower() in our_lower:
        skipped.append(w['german'])
    else:
        raw = re.sub(r'[äöüÄÖÜß ]', lambda m: {
            'ä':'ae','ö':'oe','ü':'ue','Ä':'ae','Ö':'oe','Ü':'ue','ß':'ss',' ':'_'
        }[m.group()], w['german'].lower())
        raw = re.sub(r'[^a-z0-9_]', '', raw)
        w['id'] = f"{raw}_{idx}"
        idx += 1
        added.append(w)
        our_lower.add(w['german'].lower())

vocab.extend(added)
with open(VOCAB_PATH, 'w', encoding='utf-8') as f:
    json.dump(vocab, f, ensure_ascii=False, indent=2)

print(f"Added: {len(added)}, Skipped: {len(skipped)}, Total: {len(vocab)}")
if skipped:
    print(f"Skipped: {skipped}")
