import json, re, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

VOCAB_PATH = "assets/data/vocabulary.json"

NEW_WORDS = [
    # --- Verbs from PDF alphabetical section ---
    {"german": "abbiegen", "article": "", "english": "to turn off (road)", "wordType": "verb", "plural": "", "verbForms": {"present": "biegt ab", "past": "bog ab", "participle": "abgebogen"}, "theme": "travel", "sentences": {"present": "Hier müssen wir abbiegen.", "past": "Wir bogen an der Ampel ab.", "future": "Wir werden an der nächsten Kreuzung abbiegen.", "usage1": "Biegen Sie rechts ab.", "usage2": "Das Auto bog scharf ab.", "usage3": "Wann sollen wir abbiegen?"}},
    {"german": "ablehnen", "article": "", "english": "to reject, to decline", "wordType": "verb", "plural": "", "verbForms": {"present": "lehnt ab", "past": "lehnte ab", "participle": "abgelehnt"}, "theme": "work", "sentences": {"present": "Er lehnt das Angebot ab.", "past": "Sie lehnte die Einladung ab.", "future": "Das Komitee wird den Antrag ablehnen.", "usage1": "Ich muss leider ablehnen.", "usage2": "Der Chef lehnte seinen Urlaub ab.", "usage3": "Warum hast du abgelehnt?"}},
    {"german": "abmachen", "article": "", "english": "to arrange, to agree on", "wordType": "verb", "plural": "", "verbForms": {"present": "macht ab", "past": "machte ab", "participle": "abgemacht"}, "theme": "daily_life", "sentences": {"present": "Wir machen einen Termin ab.", "past": "Sie machten aus, um 8 Uhr zu treffen.", "future": "Wir werden das später abmachen.", "usage1": "Abgemacht! Wir treffen uns um 10.", "usage2": "Was habt ihr abgemacht?", "usage3": "Lass uns einen Plan abmachen."}},
    {"german": "abnehmen", "article": "", "english": "to lose weight; to take off", "wordType": "verb", "plural": "", "verbForms": {"present": "nimmt ab", "past": "nahm ab", "participle": "abgenommen"}, "theme": "health", "sentences": {"present": "Sie nimmt gerade ab.", "past": "Er nahm fünf Kilo ab.", "future": "Ich werde abnehmen müssen.", "usage1": "Hast du abgenommen?", "usage2": "Sie möchte drei Kilo abnehmen.", "usage3": "Mit Sport kann man gut abnehmen."}},
    {"german": "absagen", "article": "", "english": "to cancel, to call off", "wordType": "verb", "plural": "", "verbForms": {"present": "sagt ab", "past": "sagte ab", "participle": "abgesagt"}, "theme": "daily_life", "sentences": {"present": "Er sagt das Treffen ab.", "past": "Sie sagte kurzfristig ab.", "future": "Ich muss leider absagen.", "usage1": "Das Konzert wurde abgesagt.", "usage2": "Bitte sagst du rechtzeitig ab?", "usage3": "Warum hast du abgesagt?"}},
    {"german": "abschließen", "article": "", "english": "to lock; to complete, to conclude", "wordType": "verb", "plural": "", "verbForms": {"present": "schließt ab", "past": "schloss ab", "participle": "abgeschlossen"}, "theme": "daily_life", "sentences": {"present": "Er schließt die Tür ab.", "past": "Sie schloss den Vertrag ab.", "future": "Er wird das Studium abschließen.", "usage1": "Hast du die Tür abgeschlossen?", "usage2": "Wir werden den Kurs abschließen.", "usage3": "Bitte schließ das Fenster ab."}},
    {"german": "anbieten", "article": "", "english": "to offer", "wordType": "verb", "plural": "", "verbForms": {"present": "bietet an", "past": "bot an", "participle": "angeboten"}, "theme": "work", "sentences": {"present": "Das Hotel bietet viele Services an.", "past": "Er bot ihr Hilfe an.", "future": "Wir werden Rabatt anbieten.", "usage1": "Darf ich Ihnen etwas anbieten?", "usage2": "Die Firma bietet gute Leistungen an.", "usage3": "Was bieten Sie an?"}},
    {"german": "anfassen", "article": "", "english": "to touch, to grasp", "wordType": "verb", "plural": "", "verbForms": {"present": "fasst an", "past": "fasste an", "participle": "angefasst"}, "theme": "daily_life", "sentences": {"present": "Er fasst das Glas an.", "past": "Das Kind fasste die heiße Herdplatte an.", "future": "Bitte fassen Sie das nicht an.", "usage1": "Nicht anfassen – frisch gestrichen!", "usage2": "Kannst du hier anfassen?", "usage3": "Sie fasste ihn sanft an der Hand an."}},
    {"german": "ankreuzen", "article": "", "english": "to check, to tick (a box)", "wordType": "verb", "plural": "", "verbForms": {"present": "kreuzt an", "past": "kreuzte an", "participle": "angekreuzt"}, "theme": "education", "sentences": {"present": "Sie kreuzt die richtige Antwort an.", "past": "Er kreuzte alle Felder an.", "future": "Bitte kreuzen Sie die Antwort an.", "usage1": "Kreuzen Sie das passende Wort an.", "usage2": "Welche Option hast du angekreuzt?", "usage3": "Die richtige Antwort muss angekreuzt werden."}},
    {"german": "anmachen", "article": "", "english": "to turn on (light, device)", "wordType": "verb", "plural": "", "verbForms": {"present": "macht an", "past": "machte an", "participle": "angemacht"}, "theme": "daily_life", "sentences": {"present": "Er macht das Licht an.", "past": "Sie machte den Fernseher an.", "future": "Ich werde die Heizung anmachen.", "usage1": "Mach bitte das Radio an.", "usage2": "Hast du den Computer angemacht?", "usage3": "Kannst du die Lampe anmachen?"}},
    {"german": "anmelden", "article": "", "english": "to register, to sign up", "wordType": "verb", "plural": "", "verbForms": {"present": "meldet an", "past": "meldete an", "participle": "angemeldet"}, "theme": "daily_life", "sentences": {"present": "Sie meldet sich für den Kurs an.", "past": "Er meldete sich beim Amt an.", "future": "Ich werde mich online anmelden.", "usage1": "Bitte melden Sie sich vorher an.", "usage2": "Hast du dich schon angemeldet?", "usage3": "Wo kann ich mich anmelden?"}},
    {"german": "annehmen", "article": "", "english": "to accept; to assume", "wordType": "verb", "plural": "", "verbForms": {"present": "nimmt an", "past": "nahm an", "participle": "angenommen"}, "theme": "work", "sentences": {"present": "Er nimmt den Job an.", "past": "Sie nahm das Angebot an.", "future": "Ich nehme an, dass er kommt.", "usage1": "Nehmen Sie meine Entschuldigung an.", "usage2": "Das Paket wurde angenommen.", "usage3": "Ich nehme an, Sie haben recht."}},
    {"german": "anpassen", "article": "", "english": "to adapt, to adjust", "wordType": "verb", "plural": "", "verbForms": {"present": "passt an", "past": "passte an", "participle": "angepasst"}, "theme": "work", "sentences": {"present": "Man muss sich ans Klima anpassen.", "past": "Sie passte den Plan an.", "future": "Wir müssen das Budget anpassen.", "usage1": "Bitte passen Sie den Termin an.", "usage2": "Er hat sich gut angepasst.", "usage3": "Die Software wurde angepasst."}},
    {"german": "anschalten", "article": "", "english": "to switch on", "wordType": "verb", "plural": "", "verbForms": {"present": "schaltet an", "past": "schaltete an", "participle": "angeschaltet"}, "theme": "daily_life", "sentences": {"present": "Sie schaltet die Lampe an.", "past": "Er schaltete den Ofen an.", "future": "Kannst du das Licht anschalten?", "usage1": "Schalte bitte den Fernseher an.", "usage2": "Die Maschine wurde angeschaltet.", "usage3": "Wie schaltet man das an?"}},
    {"german": "aufmachen", "article": "", "english": "to open (door, package)", "wordType": "verb", "plural": "", "verbForms": {"present": "macht auf", "past": "machte auf", "participle": "aufgemacht"}, "theme": "daily_life", "sentences": {"present": "Sie macht die Tür auf.", "past": "Er machte das Fenster auf.", "future": "Wir werden das Geschenk aufmachen.", "usage1": "Mach bitte die Dose auf.", "usage2": "Der Laden macht um 9 Uhr auf.", "usage3": "Kannst du das Paket aufmachen?"}},
    {"german": "aufnehmen", "article": "", "english": "to record; to pick up; to absorb", "wordType": "verb", "plural": "", "verbForms": {"present": "nimmt auf", "past": "nahm auf", "participle": "aufgenommen"}, "theme": "technology", "sentences": {"present": "Er nimmt das Video auf.", "past": "Die Kamera nahm alles auf.", "future": "Wir werden das Meeting aufnehmen.", "usage1": "Darf ich das Gespräch aufnehmen?", "usage2": "Der Boden nimmt kein Wasser mehr auf.", "usage3": "Das Album wird nächste Woche aufgenommen."}},
    {"german": "aufräumen", "article": "", "english": "to tidy up, to clear up", "wordType": "verb", "plural": "", "verbForms": {"present": "räumt auf", "past": "räumte auf", "participle": "aufgeräumt"}, "theme": "daily_life", "sentences": {"present": "Sie räumt ihr Zimmer auf.", "past": "Er räumte die Küche auf.", "future": "Ich werde am Wochenende aufräumen.", "usage1": "Räum bitte dein Zimmer auf!", "usage2": "Nach der Party mussten wir aufräumen.", "usage3": "Hast du schon aufgeräumt?"}},
    {"german": "ausgeben", "article": "", "english": "to spend (money)", "wordType": "verb", "plural": "", "verbForms": {"present": "gibt aus", "past": "gab aus", "participle": "ausgegeben"}, "theme": "daily_life", "sentences": {"present": "Er gibt viel Geld aus.", "past": "Sie gab 200 Euro aus.", "future": "Ich werde nicht so viel ausgeben.", "usage1": "Wie viel hast du ausgegeben?", "usage2": "Wir geben zu viel für Essen aus.", "usage3": "Das Geld ist schnell ausgegeben."}},
    {"german": "ausschalten", "article": "", "english": "to switch off, to turn off", "wordType": "verb", "plural": "", "verbForms": {"present": "schaltet aus", "past": "schaltete aus", "participle": "ausgeschaltet"}, "theme": "daily_life", "sentences": {"present": "Sie schaltet das Licht aus.", "past": "Er schaltete den Computer aus.", "future": "Vergiss nicht, das Licht auszuschalten.", "usage1": "Schalte bitte den Fernseher aus.", "usage2": "Alle Geräte wurden ausgeschaltet.", "usage3": "Warum hast du das ausgeschaltet?"}},
    {"german": "ausziehen", "article": "", "english": "to move out; to take off (clothes)", "wordType": "verb", "plural": "", "verbForms": {"present": "zieht aus", "past": "zog aus", "participle": "ausgezogen"}, "theme": "daily_life", "sentences": {"present": "Er zieht aus der Wohnung aus.", "past": "Sie zog letzten Monat aus.", "future": "Wir werden nächsten Monat ausziehen.", "usage1": "Wann ziehst du aus?", "usage2": "Zieh deine nassen Schuhe aus.", "usage3": "Er ist schon mit 18 ausgezogen."}},
    {"german": "backen", "article": "", "english": "to bake", "wordType": "verb", "plural": "", "verbForms": {"present": "backt", "past": "buk / backte", "participle": "gebacken"}, "theme": "food", "sentences": {"present": "Sie backt jeden Sonntag Kuchen.", "past": "Er backte Brot für die Familie.", "future": "Ich werde Kekse backen.", "usage1": "Kannst du Brot backen?", "usage2": "Der Kuchen wird bei 180°C gebacken.", "usage3": "Hast du das selbst gebacken?"}},
    {"german": "bedienen", "article": "", "english": "to serve; to operate (a machine)", "wordType": "verb", "plural": "", "verbForms": {"present": "bedient", "past": "bediente", "participle": "bedient"}, "theme": "work", "sentences": {"present": "Der Kellner bedient uns.", "past": "Sie bediente die Kunden freundlich.", "future": "Ein Roboter wird die Kasse bedienen.", "usage1": "Wie bedient man diese Maschine?", "usage2": "Er wurde sehr gut bedient.", "usage3": "Kann ich Sie bedienen?"}},
    {"german": "beenden", "article": "", "english": "to end, to finish, to terminate", "wordType": "verb", "plural": "", "verbForms": {"present": "beendet", "past": "beendete", "participle": "beendet"}, "theme": "work", "sentences": {"present": "Er beendet das Gespräch.", "past": "Sie beendete den Kurs erfolgreich.", "future": "Wir werden das Projekt beenden.", "usage1": "Wann wirst du das beenden?", "usage2": "Das Programm wurde beendet.", "usage3": "Er beendete die Beziehung."}},
    {"german": "begegnen", "article": "", "english": "to meet, to encounter", "wordType": "verb", "plural": "", "verbForms": {"present": "begegnet", "past": "begegnete", "participle": "begegnet"}, "theme": "relationships", "sentences": {"present": "Ich begegne ihm jeden Morgen.", "past": "Sie begegnete einem alten Freund.", "future": "Wir werden uns wieder begegnen.", "usage1": "Wo bist du ihm begegnet?", "usage2": "Ich bin ihr zufällig begegnet.", "usage3": "Man begegnet sich immer zweimal."}},
    {"german": "begrüßen", "article": "", "english": "to greet, to welcome", "wordType": "verb", "plural": "", "verbForms": {"present": "begrüßt", "past": "begrüßte", "participle": "begrüßt"}, "theme": "relationships", "sentences": {"present": "Er begrüßt die Gäste herzlich.", "past": "Sie begrüßte ihn mit einem Lächeln.", "future": "Der Direktor wird uns begrüßen.", "usage1": "Wie begrüßt man in Deutschland?", "usage2": "Wir wurden sehr freundlich begrüßt.", "usage3": "Bitte begrüßen Sie unsere Gäste."}},
    {"german": "benutzen", "article": "", "english": "to use", "wordType": "verb", "plural": "", "verbForms": {"present": "benutzt", "past": "benutzte", "participle": "benutzt"}, "theme": "daily_life", "sentences": {"present": "Er benutzt täglich das Fahrrad.", "past": "Sie benutzte das Wörterbuch.", "future": "Wir werden das neue System benutzen.", "usage1": "Darf ich Ihr Telefon benutzen?", "usage2": "Dieses Werkzeug wird selten benutzt.", "usage3": "Wie benutzt man das?"}},
    {"german": "beschreiben", "article": "", "english": "to describe", "wordType": "verb", "plural": "", "verbForms": {"present": "beschreibt", "past": "beschrieb", "participle": "beschrieben"}, "theme": "language_exam", "sentences": {"present": "Sie beschreibt das Bild genau.", "past": "Er beschrieb den Täter.", "future": "Kannst du das beschreiben?", "usage1": "Bitte beschreiben Sie das Problem.", "usage2": "Der Weg wurde gut beschrieben.", "usage3": "Wie würdest du das beschreiben?"}},
    {"german": "bestätigen", "article": "", "english": "to confirm", "wordType": "verb", "plural": "", "verbForms": {"present": "bestätigt", "past": "bestätigte", "participle": "bestätigt"}, "theme": "work", "sentences": {"present": "Er bestätigt den Termin.", "past": "Sie bestätigte die Reservierung.", "future": "Wir werden die Buchung bestätigen.", "usage1": "Bitte bestätigen Sie Ihre E-Mail.", "usage2": "Die Teilnahme wurde bestätigt.", "usage3": "Können Sie das bestätigen?"}},
    {"german": "bewerben", "article": "", "english": "to apply (for a job)", "wordType": "verb", "plural": "", "verbForms": {"present": "bewirbt sich", "past": "bewarb sich", "participle": "beworben"}, "theme": "work", "sentences": {"present": "Er bewirbt sich um die Stelle.", "past": "Sie bewarb sich bei vielen Firmen.", "future": "Ich werde mich bewerben.", "usage1": "Wo hast du dich beworben?", "usage2": "Ich möchte mich um den Job bewerben.", "usage3": "Wie bewirbt man sich richtig?"}},
    {"german": "bewohnen", "article": "", "english": "to live in, to inhabit", "wordType": "verb", "plural": "", "verbForms": {"present": "bewohnt", "past": "bewohnte", "participle": "bewohnt"}, "theme": "daily_life", "sentences": {"present": "Familie Müller bewohnt das Haus.", "past": "Sie bewohnten die Wohnung 10 Jahre.", "future": "Wir werden die neue Wohnung bewohnen.", "usage1": "Wer bewohnt das Gebäude?", "usage2": "Das Haus ist seit Jahren bewohnt.", "usage3": "Sie bewohnen ein großes Apartment."}},
    {"german": "drucken", "article": "", "english": "to print", "wordType": "verb", "plural": "", "verbForms": {"present": "druckt", "past": "druckte", "participle": "gedruckt"}, "theme": "technology", "sentences": {"present": "Er druckt das Dokument aus.", "past": "Sie druckte die Einladungen.", "future": "Ich werde die Fotos drucken.", "usage1": "Kannst du das bitte drucken?", "usage2": "Das Buch wurde 2020 gedruckt.", "usage3": "Der Drucker druckt langsam."}},
    {"german": "einführen", "article": "", "english": "to introduce; to implement", "wordType": "verb", "plural": "", "verbForms": {"present": "führt ein", "past": "führte ein", "participle": "eingeführt"}, "theme": "work", "sentences": {"present": "Die Firma führt eine neue Regel ein.", "past": "Sie führte das System ein.", "future": "Wir werden das Verfahren einführen.", "usage1": "Wann wird das eingeführt?", "usage2": "Das neue Gesetz wurde eingeführt.", "usage3": "Wie soll man das einführen?"}},
    {"german": "einladen", "article": "", "english": "to invite", "wordType": "verb", "plural": "", "verbForms": {"present": "lädt ein", "past": "lud ein", "participle": "eingeladen"}, "theme": "relationships", "sentences": {"present": "Sie lädt ihn zum Essen ein.", "past": "Er lud alle Freunde ein.", "future": "Ich werde dich zum Geburtstag einladen.", "usage1": "Darf ich dich einladen?", "usage2": "Du bist herzlich eingeladen.", "usage3": "Wen sollen wir einladen?"}},
    {"german": "einschlafen", "article": "", "english": "to fall asleep", "wordType": "verb", "plural": "", "verbForms": {"present": "schläft ein", "past": "schlief ein", "participle": "eingeschlafen"}, "theme": "health", "sentences": {"present": "Er schläft immer schnell ein.", "past": "Das Baby schlief sofort ein.", "future": "Ich werde heute früh einschlafen.", "usage1": "Kannst du nicht einschlafen?", "usage2": "Sie schlief beim Film ein.", "usage3": "Mit Musik schlafe ich besser ein."}},
    {"german": "empfangen", "article": "", "english": "to receive; to welcome", "wordType": "verb", "plural": "", "verbForms": {"present": "empfängt", "past": "empfing", "participle": "empfangen"}, "theme": "work", "sentences": {"present": "Er empfängt die Gäste.", "past": "Sie empfing das Paket.", "future": "Der Chef wird uns empfangen.", "usage1": "Haben Sie das Paket empfangen?", "usage2": "Wir wurden herzlich empfangen.", "usage3": "Wo werden wir empfangen?"}},
    {"german": "entscheiden", "article": "", "english": "to decide", "wordType": "verb", "plural": "", "verbForms": {"present": "entscheidet", "past": "entschied", "participle": "entschieden"}, "theme": "daily_life", "sentences": {"present": "Er entscheidet sich für das Rote.", "past": "Sie entschied schnell.", "future": "Wir werden das morgen entscheiden.", "usage1": "Hast du dich entschieden?", "usage2": "Das Gericht hat entschieden.", "usage3": "Ich kann mich nicht entscheiden."}},
    {"german": "erklären", "article": "", "english": "to explain", "wordType": "verb", "plural": "", "verbForms": {"present": "erklärt", "past": "erklärte", "participle": "erklärt"}, "theme": "education", "sentences": {"present": "Der Lehrer erklärt die Aufgabe.", "past": "Sie erklärte ihm den Weg.", "future": "Ich werde es dir erklären.", "usage1": "Kannst du das erklären?", "usage2": "Die Regel wurde gut erklärt.", "usage3": "Wie erklärt man das?"}},
    {"german": "erhöhen", "article": "", "english": "to increase, to raise", "wordType": "verb", "plural": "", "verbForms": {"present": "erhöht", "past": "erhöhte", "participle": "erhöht"}, "theme": "work", "sentences": {"present": "Die Firma erhöht die Gehälter.", "past": "Sie erhöhten die Preise.", "future": "Die Miete wird erhöht.", "usage1": "Das Risiko wurde erhöht.", "usage2": "Der Preis wurde um 10% erhöht.", "usage3": "Wann wird das Gehalt erhöht?"}},
    {"german": "erledigen", "article": "", "english": "to handle, to take care of, to complete", "wordType": "verb", "plural": "", "verbForms": {"present": "erledigt", "past": "erledigte", "participle": "erledigt"}, "theme": "work", "sentences": {"present": "Er erledigt seine Aufgaben.", "past": "Sie erledigte alle Einkäufe.", "future": "Ich werde das morgen erledigen.", "usage1": "Das ist erledigt.", "usage2": "Haben Sie das erledigt?", "usage3": "Bitte erledige das bis Freitag."}},
    {"german": "ernähren", "article": "", "english": "to feed, to nourish; to eat (sich ernähren)", "wordType": "verb", "plural": "", "verbForms": {"present": "ernährt sich", "past": "ernährte sich", "participle": "ernährt"}, "theme": "health", "sentences": {"present": "Sie ernährt sich gesund.", "past": "Er ernährte sich von Gemüse.", "future": "Ich werde mich besser ernähren.", "usage1": "Wie ernährst du dich?", "usage2": "Veganer ernähren sich ohne Fleisch.", "usage3": "Gesund zu essen ist wichtig."}},
    {"german": "erreichen", "article": "", "english": "to reach, to achieve, to attain", "wordType": "verb", "plural": "", "verbForms": {"present": "erreicht", "past": "erreichte", "participle": "erreicht"}, "theme": "work", "sentences": {"present": "Er erreicht das Ziel.", "past": "Sie erreichte den Bahnhof rechtzeitig.", "future": "Wir werden unser Ziel erreichen.", "usage1": "Ich kann Sie nicht erreichen.", "usage2": "Hast du dein Ziel erreicht?", "usage3": "Den Gipfel zu erreichen war schwer."}},
    {"german": "erschrecken", "article": "", "english": "to frighten, to be startled", "wordType": "verb", "plural": "", "verbForms": {"present": "erschrickt", "past": "erschrak", "participle": "erschrocken"}, "theme": "daily_life", "sentences": {"present": "Er erschrickt bei jedem Geräusch.", "past": "Sie erschrak sehr.", "future": "Du wirst erschrecken.", "usage1": "Ich hab mich erschrocken!", "usage2": "Das hat mich erschreckt.", "usage3": "Er ist leicht zu erschrecken."}},
    {"german": "erzeugen", "article": "", "english": "to generate, to produce", "wordType": "verb", "plural": "", "verbForms": {"present": "erzeugt", "past": "erzeugte", "participle": "erzeugt"}, "theme": "environment", "sentences": {"present": "Solaranlagen erzeugen Strom.", "past": "Die Fabrik erzeugte viel Abfall.", "future": "Windkraft wird mehr Energie erzeugen.", "usage1": "Wie wird Energie erzeugt?", "usage2": "Der Motor erzeugt Wärme.", "usage3": "Das erzeugt zu viel Lärm."}},
    {"german": "existieren", "article": "", "english": "to exist", "wordType": "verb", "plural": "", "verbForms": {"present": "existiert", "past": "existierte", "participle": "existiert"}, "theme": "other", "sentences": {"present": "Das Problem existiert noch.", "past": "Die Firma existierte 50 Jahre.", "future": "Das wird nicht mehr lange existieren.", "usage1": "Existiert das wirklich?", "usage2": "Das Unternehmen existiert seit 1990.", "usage3": "Können wir so existieren?"}},
    {"german": "fehlen", "article": "", "english": "to be missing, to be absent; to be lacking", "wordType": "verb", "plural": "", "verbForms": {"present": "fehlt", "past": "fehlte", "participle": "gefehlt"}, "theme": "daily_life", "sentences": {"present": "Du fehlst mir sehr.", "past": "Er fehlte einen Monat lang.", "future": "Das wird nicht fehlen.", "usage1": "Was fehlt dir?", "usage2": "Er hat drei Tage in der Schule gefehlt.", "usage3": "Mir fehlt das Geld dafür."}},
    {"german": "flüstern", "article": "", "english": "to whisper", "wordType": "verb", "plural": "", "verbForms": {"present": "flüstert", "past": "flüsterte", "participle": "geflüstert"}, "theme": "relationships", "sentences": {"present": "Sie flüstert etwas in sein Ohr.", "past": "Er flüsterte ihr zu.", "future": "Flüster bitte, die anderen schlafen.", "usage1": "Warum flüsterst du?", "usage2": "Sie flüsterten miteinander.", "usage3": "Er hat es ihr geflüstert."}},
    {"german": "fördern", "article": "", "english": "to promote, to support, to encourage", "wordType": "verb", "plural": "", "verbForms": {"present": "fördert", "past": "förderte", "participle": "gefördert"}, "theme": "education", "sentences": {"present": "Die Schule fördert Talente.", "past": "Der Staat förderte das Projekt.", "future": "Wir werden Kreativität fördern.", "usage1": "Das Programm fördert Schüler.", "usage2": "Wie wird das gefördert?", "usage3": "Können wir das fördern?"}},
    {"german": "genehmigen", "article": "", "english": "to approve, to authorize", "wordType": "verb", "plural": "", "verbForms": {"present": "genehmigt", "past": "genehmigte", "participle": "genehmigt"}, "theme": "work", "sentences": {"present": "Der Chef genehmigt den Urlaub.", "past": "Sie genehmigte den Antrag.", "future": "Das Amt wird das genehmigen.", "usage1": "Wurde der Antrag genehmigt?", "usage2": "Der Bau wurde genehmigt.", "usage3": "Wann wird das genehmigt?"}},
    {"german": "gewinnen", "article": "", "english": "to win; to gain", "wordType": "verb", "plural": "", "verbForms": {"present": "gewinnt", "past": "gewann", "participle": "gewonnen"}, "theme": "other", "sentences": {"present": "Unsere Mannschaft gewinnt oft.", "past": "Er gewann das Turnier.", "future": "Wir werden das Spiel gewinnen.", "usage1": "Wer hat gewonnen?", "usage2": "Sie gewann den ersten Preis.", "usage3": "Es ist schwer zu gewinnen."}},
    {"german": "gratulieren", "article": "", "english": "to congratulate", "wordType": "verb", "plural": "", "verbForms": {"present": "gratuliert", "past": "gratulierte", "participle": "gratuliert"}, "theme": "relationships", "sentences": {"present": "Er gratuliert ihr zum Geburtstag.", "past": "Alle gratulierten ihr zur Prüfung.", "future": "Ich werde dir gratulieren.", "usage1": "Herzlichen Glückwunsch, ich gratuliere!", "usage2": "Hast du ihm schon gratuliert?", "usage3": "Wir möchten dir gratulieren."}},
    {"german": "klettern", "article": "", "english": "to climb", "wordType": "verb", "plural": "", "verbForms": {"present": "klettert", "past": "kletterte", "participle": "geklettert"}, "theme": "travel", "sentences": {"present": "Die Kinder klettern auf den Baum.", "past": "Er kletterte auf den Berg.", "future": "Wir werden morgen klettern.", "usage1": "Kannst du klettern?", "usage2": "Sie kletterten die Felswand hoch.", "usage3": "Klettern macht Spaß."}},
    {"german": "kündigen", "article": "", "english": "to give notice, to quit, to cancel (contract)", "wordType": "verb", "plural": "", "verbForms": {"present": "kündigt", "past": "kündigte", "participle": "gekündigt"}, "theme": "work", "sentences": {"present": "Er kündigt seinen Job.", "past": "Sie kündigte die Wohnung.", "future": "Ich werde den Vertrag kündigen.", "usage1": "Er hat gekündigt.", "usage2": "Wann muss man kündigen?", "usage3": "Die Firma hat ihm gekündigt."}},
    {"german": "laden", "article": "", "english": "to load; to charge (battery)", "wordType": "verb", "plural": "", "verbForms": {"present": "lädt", "past": "lud", "participle": "geladen"}, "theme": "technology", "sentences": {"present": "Das Handy lädt gerade.", "past": "Er lud den Akku.", "future": "Ich werde das Gerät laden.", "usage1": "Ist das Handy schon geladen?", "usage2": "Bitte das Telefon laden.", "usage3": "Wie lange braucht es zum Laden?"}},
    {"german": "leisten", "article": "", "english": "to perform, to achieve; to afford (sich leisten)", "wordType": "verb", "plural": "", "verbForms": {"present": "leistet", "past": "leistete", "participle": "geleistet"}, "theme": "work", "sentences": {"present": "Er leistet gute Arbeit.", "past": "Sie leistete viel für die Firma.", "future": "Das kannst du dir leisten.", "usage1": "Kann ich mir das leisten?", "usage2": "Er hat Großes geleistet.", "usage3": "Das können wir nicht leisten."}},
    {"german": "lügen", "article": "", "english": "to lie, to tell a lie", "wordType": "verb", "plural": "", "verbForms": {"present": "lügt", "past": "log", "participle": "gelogen"}, "theme": "relationships", "sentences": {"present": "Du lügst mich an.", "past": "Er log sie an.", "future": "Lüg mich nicht an.", "usage1": "Lügen ist falsch.", "usage2": "Er hat gelogen.", "usage3": "Warum hast du gelogen?"}},
    {"german": "messen", "article": "", "english": "to measure", "wordType": "verb", "plural": "", "verbForms": {"present": "misst", "past": "maß", "participle": "gemessen"}, "theme": "daily_life", "sentences": {"present": "Er misst die Temperatur.", "past": "Sie maß den Raum.", "future": "Wir werden das Zimmer messen.", "usage1": "Haben Sie Fieber gemessen?", "usage2": "Bitte miss die Länge.", "usage3": "Wie wird das gemessen?"}},
    {"german": "mieten", "article": "", "english": "to rent (from someone)", "wordType": "verb", "plural": "", "verbForms": {"present": "mietet", "past": "mietete", "participle": "gemietet"}, "theme": "daily_life", "sentences": {"present": "Er mietet eine Wohnung.", "past": "Sie mieteten ein Auto.", "future": "Wir werden eine Ferienwohnung mieten.", "usage1": "Hast du das Fahrrad gemietet?", "usage2": "Die Wohnung ist gemietet.", "usage3": "Kann man hier ein Fahrrad mieten?"}},
    {"german": "mitteilen", "article": "", "english": "to inform, to notify, to communicate", "wordType": "verb", "plural": "", "verbForms": {"present": "teilt mit", "past": "teilte mit", "participle": "mitgeteilt"}, "theme": "work", "sentences": {"present": "Er teilt ihr die Neuigkeit mit.", "past": "Sie teilte uns den Termin mit.", "future": "Ich werde Ihnen das mitteilen.", "usage1": "Bitte teilen Sie uns das mit.", "usage2": "Das wurde uns nicht mitgeteilt.", "usage3": "Wann wirst du es mitteilen?"}},
    {"german": "nachdenken", "article": "", "english": "to think (about), to reflect", "wordType": "verb", "plural": "", "verbForms": {"present": "denkt nach", "past": "dachte nach", "participle": "nachgedacht"}, "theme": "daily_life", "sentences": {"present": "Er denkt über die Frage nach.", "past": "Sie dachte lange nach.", "future": "Ich werde darüber nachdenken.", "usage1": "Denk mal nach!", "usage2": "Hast du darüber nachgedacht?", "usage3": "Man muss gut nachdenken."}},
    {"german": "nennen", "article": "", "english": "to name, to call", "wordType": "verb", "plural": "", "verbForms": {"present": "nennt", "past": "nannte", "participle": "genannt"}, "theme": "language_exam", "sentences": {"present": "Er nennt drei Beispiele.", "past": "Sie nannte ihn beim Vornamen.", "future": "Kannst du mir ein Beispiel nennen?", "usage1": "Wie nennt man das?", "usage2": "Nenn mir einen Grund.", "usage3": "Das wird auch X genannt."}},
    {"german": "nutzen", "article": "", "english": "to use, to make use of", "wordType": "verb", "plural": "", "verbForms": {"present": "nutzt", "past": "nutzte", "participle": "genutzt"}, "theme": "technology", "sentences": {"present": "Er nutzt die App täglich.", "past": "Sie nutzte die Chance.", "future": "Wir werden das System nutzen.", "usage1": "Wie nutzt man das?", "usage2": "Die Gelegenheit wurde genutzt.", "usage3": "Wofür nutzt du das?"}},
    {"german": "pflegen", "article": "", "english": "to care for, to tend, to maintain", "wordType": "verb", "plural": "", "verbForms": {"present": "pflegt", "past": "pflegte", "participle": "gepflegt"}, "theme": "health", "sentences": {"present": "Sie pflegt ihre alte Mutter.", "past": "Er pflegte den Garten sorgfältig.", "future": "Wir werden die Kranken pflegen.", "usage1": "Wer pflegt Sie?", "usage2": "Der Garten wird gut gepflegt.", "usage3": "Haben Sie jemanden der Sie pflegt?"}},
    {"german": "planen", "article": "", "english": "to plan", "wordType": "verb", "plural": "", "verbForms": {"present": "plant", "past": "plante", "participle": "geplant"}, "theme": "work", "sentences": {"present": "Er plant seine Reise.", "past": "Sie plante die Party sorgfältig.", "future": "Wir werden das Projekt planen.", "usage1": "Was hast du geplant?", "usage2": "Alles wurde gut geplant.", "usage3": "Wie soll das geplant werden?"}},
    {"german": "probieren", "article": "", "english": "to try, to taste", "wordType": "verb", "plural": "", "verbForms": {"present": "probiert", "past": "probierte", "participle": "probiert"}, "theme": "food", "sentences": {"present": "Er probiert das neue Gericht.", "past": "Sie probierte den Wein.", "future": "Möchtest du das probieren?", "usage1": "Probier doch mal!", "usage2": "Hast du das schon probiert?", "usage3": "Ich möchte das probieren."}},
    {"german": "schützen", "article": "", "english": "to protect", "wordType": "verb", "plural": "", "verbForms": {"present": "schützt", "past": "schützte", "participle": "geschützt"}, "theme": "environment", "sentences": {"present": "Wir müssen die Umwelt schützen.", "past": "Er schützte sie vor dem Regen.", "future": "Wir werden die Daten schützen.", "usage1": "Wie kann man sich schützen?", "usage2": "Die Kinder wurden geschützt.", "usage3": "Das muss geschützt werden."}},
    {"german": "stammen", "article": "", "english": "to come from, to originate", "wordType": "verb", "plural": "", "verbForms": {"present": "stammt", "past": "stammte", "participle": "gestammt"}, "theme": "other", "sentences": {"present": "Er stammt aus Bayern.", "past": "Das Wort stammte aus dem Lateinischen.", "future": "Wo wirst du herstammen?", "usage1": "Woher stammen Sie?", "usage2": "Das Rezept stammt von meiner Oma.", "usage3": "Das stammt aus dem 18. Jahrhundert."}},
    {"german": "stattfinden", "article": "", "english": "to take place, to occur", "wordType": "verb", "plural": "", "verbForms": {"present": "findet statt", "past": "fand statt", "participle": "stattgefunden"}, "theme": "culture", "sentences": {"present": "Das Konzert findet morgen statt.", "past": "Das Fest fand im Park statt.", "future": "Die Prüfung wird nächste Woche stattfinden.", "usage1": "Wo findet das statt?", "usage2": "Die Veranstaltung fand statt.", "usage3": "Wann findet das Treffen statt?"}},
    {"german": "stören", "article": "", "english": "to disturb, to bother", "wordType": "verb", "plural": "", "verbForms": {"present": "stört", "past": "störte", "participle": "gestört"}, "theme": "daily_life", "sentences": {"present": "Der Lärm stört mich.", "past": "Er störte den Unterricht.", "future": "Das wird mich nicht stören.", "usage1": "Darf ich Sie kurz stören?", "usage2": "Bitte nicht stören!", "usage3": "Das stört mich sehr."}},
    {"german": "tauschen", "article": "", "english": "to exchange, to swap", "wordType": "verb", "plural": "", "verbForms": {"present": "tauscht", "past": "tauschte", "participle": "getauscht"}, "theme": "daily_life", "sentences": {"present": "Er tauscht seine Bücher.", "past": "Sie tauschten die Rollen.", "future": "Ich werde das umtauschen.", "usage1": "Möchtest du tauschen?", "usage2": "Wir haben die Plätze getauscht.", "usage3": "Kann man das tauschen?"}},
    {"german": "teilen", "article": "", "english": "to share; to divide", "wordType": "verb", "plural": "", "verbForms": {"present": "teilt", "past": "teilte", "participle": "geteilt"}, "theme": "relationships", "sentences": {"present": "Sie teilt ihr Essen.", "past": "Er teilte das Geld mit ihr.", "future": "Wir werden die Kosten teilen.", "usage1": "Kannst du das teilen?", "usage2": "Bitte teile mit mir.", "usage3": "Das haben wir geteilt."}},
    {"german": "trennen", "article": "", "english": "to separate, to divide; to break up", "wordType": "verb", "plural": "", "verbForms": {"present": "trennt", "past": "trennte", "participle": "getrennt"}, "theme": "relationships", "sentences": {"present": "Sie trennt sich von ihm.", "past": "Er trennte Müll sorgfältig.", "future": "Wir werden uns trennen.", "usage1": "Wann haben Sie sich getrennt?", "usage2": "Müll muss getrennt werden.", "usage3": "Sie haben sich getrennt."}},
    {"german": "trocknen", "article": "", "english": "to dry", "wordType": "verb", "plural": "", "verbForms": {"present": "trocknet", "past": "trocknete", "participle": "getrocknet"}, "theme": "daily_life", "sentences": {"present": "Die Wäsche trocknet draußen.", "past": "Er trocknete die Hände.", "future": "Die Kleidung wird trocknen.", "usage1": "Trockne deine Haare.", "usage2": "Ist die Wäsche schon trocken?", "usage3": "Das trocknet schnell an der Sonne."}},
    {"german": "überweisen", "article": "", "english": "to transfer (money)", "wordType": "verb", "plural": "", "verbForms": {"present": "überweist", "past": "überwies", "participle": "überwiesen"}, "theme": "daily_life", "sentences": {"present": "Er überweist die Miete.", "past": "Sie überwies das Geld.", "future": "Ich werde den Betrag überweisen.", "usage1": "Bitte überweisen Sie bis Montag.", "usage2": "Das Geld wurde überwiesen.", "usage3": "Wie kann ich das überweisen?"}},
    {"german": "umsteigen", "article": "", "english": "to change (trains/buses), to transfer", "wordType": "verb", "plural": "", "verbForms": {"present": "steigt um", "past": "stieg um", "participle": "umgestiegen"}, "theme": "travel", "sentences": {"present": "Er steigt am Hauptbahnhof um.", "past": "Sie stieg in München um.", "future": "Wir müssen umsteigen.", "usage1": "Wo muss ich umsteigen?", "usage2": "Einmal umsteigen bis zum Ziel.", "usage3": "Muss ich hier umsteigen?"}},
    {"german": "umziehen", "article": "", "english": "to move (house); to change clothes", "wordType": "verb", "plural": "", "verbForms": {"present": "zieht um", "past": "zog um", "participle": "umgezogen"}, "theme": "daily_life", "sentences": {"present": "Sie zieht in eine neue Stadt um.", "past": "Er zog letztes Jahr um.", "future": "Wir werden nächsten Monat umziehen.", "usage1": "Wann zieht ihr um?", "usage2": "Ich bin gerade umgezogen.", "usage3": "Warum willst du umziehen?"}},
    {"german": "unterschreiben", "article": "", "english": "to sign (a document)", "wordType": "verb", "plural": "", "verbForms": {"present": "unterschreibt", "past": "unterschrieb", "participle": "unterschrieben"}, "theme": "work", "sentences": {"present": "Er unterschreibt den Vertrag.", "past": "Sie unterschrieb alle Dokumente.", "future": "Wir werden den Vertrag unterschreiben.", "usage1": "Bitte hier unterschreiben.", "usage2": "Hast du unterschrieben?", "usage3": "Der Vertrag wurde unterschrieben."}},
    {"german": "verbessern", "article": "", "english": "to improve; to correct", "wordType": "verb", "plural": "", "verbForms": {"present": "verbessert", "past": "verbesserte", "participle": "verbessert"}, "theme": "education", "sentences": {"present": "Sie verbessert ihren Aufsatz.", "past": "Er verbesserte seine Note.", "future": "Ich werde mein Deutsch verbessern.", "usage1": "Wie kann ich mich verbessern?", "usage2": "Die Situation hat sich verbessert.", "usage3": "Darf ich Sie verbessern?"}},
    {"german": "verbinden", "article": "", "english": "to connect; to bandage", "wordType": "verb", "plural": "", "verbForms": {"present": "verbindet", "past": "verband", "participle": "verbunden"}, "theme": "technology", "sentences": {"present": "Er verbindet die Kabel.", "past": "Sie verband seine Wunde.", "future": "Wir werden das Netzwerk verbinden.", "usage1": "Ich verbinde Sie weiter.", "usage2": "Die Straße verbindet zwei Städte.", "usage3": "Wie verbindet man das?"}},
    {"german": "verdienen", "article": "", "english": "to earn; to deserve", "wordType": "verb", "plural": "", "verbForms": {"present": "verdient", "past": "verdiente", "participle": "verdient"}, "theme": "work", "sentences": {"present": "Er verdient gut.", "past": "Sie verdiente 2000 Euro.", "future": "Ich werde mehr verdienen.", "usage1": "Was verdienst du?", "usage2": "Das hast du verdient.", "usage3": "Wie viel verdient man dabei?"}},
    {"german": "vergessen", "article": "", "english": "to forget", "wordType": "verb", "plural": "", "verbForms": {"present": "vergisst", "past": "vergaß", "participle": "vergessen"}, "theme": "daily_life", "sentences": {"present": "Er vergisst immer alles.", "past": "Sie vergaß ihren Schlüssel.", "future": "Vergiss das nicht!", "usage1": "Ich hab das total vergessen.", "usage2": "Das werde ich nie vergessen.", "usage3": "Hast du das vergessen?"}},
    {"german": "vergleichen", "article": "", "english": "to compare", "wordType": "verb", "plural": "", "verbForms": {"present": "vergleicht", "past": "verglich", "participle": "verglichen"}, "theme": "language_exam", "sentences": {"present": "Sie vergleicht die Preise.", "past": "Er verglich die beiden Texte.", "future": "Bitte vergleichen Sie die Angebote.", "usage1": "Vergleiche nicht alles.", "usage2": "Wie vergleicht man das?", "usage3": "Das lässt sich nicht vergleichen."}},
    {"german": "verlassen", "article": "", "english": "to leave; to rely on (sich verlassen auf)", "wordType": "verb", "plural": "", "verbForms": {"present": "verlässt", "past": "verließ", "participle": "verlassen"}, "theme": "relationships", "sentences": {"present": "Er verlässt die Stadt.", "past": "Sie verließ ihn.", "future": "Ich werde die Firma verlassen.", "usage1": "Du kannst dich auf mich verlassen.", "usage2": "Wann hast du das Haus verlassen?", "usage3": "Er hat mich verlassen."}},
    {"german": "verletzen", "article": "", "english": "to injure, to hurt", "wordType": "verb", "plural": "", "verbForms": {"present": "verletzt", "past": "verletzte", "participle": "verletzt"}, "theme": "health", "sentences": {"present": "Er verletzt sich beim Sport.", "past": "Sie verletzte sich am Knie.", "future": "Pass auf, dass du dich nicht verletzt.", "usage1": "Bist du verletzt?", "usage2": "Er wurde schwer verletzt.", "usage3": "Das hat ihn verletzt."}},
    {"german": "vermeiden", "article": "", "english": "to avoid", "wordType": "verb", "plural": "", "verbForms": {"present": "vermeidet", "past": "vermied", "participle": "vermieden"}, "theme": "health", "sentences": {"present": "Er vermeidet Zucker.", "past": "Sie vermied den Kontakt.", "future": "Ich werde Stress vermeiden.", "usage1": "Das muss man vermeiden.", "usage2": "Konflikte wurden vermieden.", "usage3": "Wie kann man das vermeiden?"}},
    {"german": "vermissen", "article": "", "english": "to miss (someone/something)", "wordType": "verb", "plural": "", "verbForms": {"present": "vermisst", "past": "vermisste", "participle": "vermisst"}, "theme": "relationships", "sentences": {"present": "Er vermisst seine Familie.", "past": "Sie vermisste ihn sehr.", "future": "Ich werde dich vermissen.", "usage1": "Ich vermisse dich.", "usage2": "Das habe ich sehr vermisst.", "usage3": "Vermisst du deine Heimat?"}},
    {"german": "verpassen", "article": "", "english": "to miss (bus, train, opportunity)", "wordType": "verb", "plural": "", "verbForms": {"present": "verpasst", "past": "verpasste", "participle": "verpasst"}, "theme": "travel", "sentences": {"present": "Er verpasst den Zug.", "past": "Sie verpasste den Anschluss.", "future": "Du wirst den Bus verpassen.", "usage1": "Ich habe den Zug verpasst.", "usage2": "Das darfst du nicht verpassen.", "usage3": "Hast du das Event verpasst?"}},
    {"german": "versuchen", "article": "", "english": "to try, to attempt", "wordType": "verb", "plural": "", "verbForms": {"present": "versucht", "past": "versuchte", "participle": "versucht"}, "theme": "daily_life", "sentences": {"present": "Er versucht, das Problem zu lösen.", "past": "Sie versuchte es mehrmals.", "future": "Ich werde es versuchen.", "usage1": "Versuch es einfach.", "usage2": "Haben Sie es versucht?", "usage3": "Es ist einen Versuch wert."}},
    {"german": "vorstellen", "article": "", "english": "to introduce; to imagine (sich vorstellen)", "wordType": "verb", "plural": "", "verbForms": {"present": "stellt vor", "past": "stellte vor", "participle": "vorgestellt"}, "theme": "relationships", "sentences": {"present": "Er stellt sich vor.", "past": "Sie stellte ihn dem Chef vor.", "future": "Darf ich mich vorstellen?", "usage1": "Ich stelle mich kurz vor.", "usage2": "Stell dir das vor!", "usage3": "Kann ich Ihnen jemanden vorstellen?"}},
    {"german": "wandern", "article": "", "english": "to hike; to wander", "wordType": "verb", "plural": "", "verbForms": {"present": "wandert", "past": "wanderte", "participle": "gewandert"}, "theme": "travel", "sentences": {"present": "Sie wandern jeden Sonntag.", "past": "Er wanderte durch die Alpen.", "future": "Wir werden im Urlaub wandern.", "usage1": "Gehst du gern wandern?", "usage2": "Wir sind stundenlang gewandert.", "usage3": "Wie weit wollen wir wandern?"}},
    {"german": "wechseln", "article": "", "english": "to change, to switch, to exchange", "wordType": "verb", "plural": "", "verbForms": {"present": "wechselt", "past": "wechselte", "participle": "gewechselt"}, "theme": "daily_life", "sentences": {"present": "Er wechselt den Job.", "past": "Sie wechselte die Schule.", "future": "Ich werde die Wohnung wechseln.", "usage1": "Kannst du Geld wechseln?", "usage2": "Das Wetter wechselt schnell.", "usage3": "Wann hast du gewechselt?"}},
    {"german": "wiederholen", "article": "", "english": "to repeat; to revise", "wordType": "verb", "plural": "", "verbForms": {"present": "wiederholt", "past": "wiederholte", "participle": "wiederholt"}, "theme": "education", "sentences": {"present": "Er wiederholt den Stoff.", "past": "Sie wiederholte ihre Frage.", "future": "Wir werden das wiederholen.", "usage1": "Bitte wiederholen Sie das.", "usage2": "Ich habe nicht verstanden, können Sie wiederholen?", "usage3": "Das darf sich nicht wiederholen."}},
    {"german": "wünschen", "article": "", "english": "to wish", "wordType": "verb", "plural": "", "verbForms": {"present": "wünscht", "past": "wünschte", "participle": "gewünscht"}, "theme": "relationships", "sentences": {"present": "Ich wünsche dir alles Gute.", "past": "Er wünschte sich ein Fahrrad.", "future": "Was wirst du dir wünschen?", "usage1": "Was wünschst du dir?", "usage2": "Ich wünsche Ihnen eine gute Reise.", "usage3": "Das hätte ich mir gewünscht."}},
    {"german": "zeichnen", "article": "", "english": "to draw", "wordType": "verb", "plural": "", "verbForms": {"present": "zeichnet", "past": "zeichnete", "participle": "gezeichnet"}, "theme": "culture", "sentences": {"present": "Er zeichnet ein Porträt.", "past": "Sie zeichnete einen Stadtplan.", "future": "Ich werde das zeichnen.", "usage1": "Kannst du zeichnen?", "usage2": "Er hat das selbst gezeichnet.", "usage3": "Zeichne mir bitte eine Karte."}},
    {"german": "zerstören", "article": "", "english": "to destroy", "wordType": "verb", "plural": "", "verbForms": {"present": "zerstört", "past": "zerstörte", "participle": "zerstört"}, "theme": "environment", "sentences": {"present": "Der Sturm zerstört Häuser.", "past": "Das Feuer zerstörte das Gebäude.", "future": "Das wird die Umwelt zerstören.", "usage1": "Alles wurde zerstört.", "usage2": "Bitte nichts zerstören.", "usage3": "Das hat alles zerstört."}},
    {"german": "zuhören", "article": "", "english": "to listen (attentively)", "wordType": "verb", "plural": "", "verbForms": {"present": "hört zu", "past": "hörte zu", "participle": "zugehört"}, "theme": "relationships", "sentences": {"present": "Er hört ihr genau zu.", "past": "Sie hörte aufmerksam zu.", "future": "Bitte hör zu!", "usage1": "Kannst du mir zuhören?", "usage2": "Hör mal zu!", "usage3": "Niemand hat zugehört."}},
    {"german": "ärgern", "article": "", "english": "to annoy; to be annoyed (sich ärgern)", "wordType": "verb", "plural": "", "verbForms": {"present": "ärgert", "past": "ärgerte", "participle": "geärgert"}, "theme": "relationships", "sentences": {"present": "Das ärgert mich.", "past": "Er ärgerte sich über die Note.", "future": "Das wird dich ärgern.", "usage1": "Ich ärgere mich sehr.", "usage2": "Warum ärgerst du dich?", "usage3": "Das ärgert mich wirklich."}},
    {"german": "überlegen", "article": "", "english": "to think over, to consider", "wordType": "verb", "plural": "", "verbForms": {"present": "überlegt", "past": "überlegte", "participle": "überlegt"}, "theme": "daily_life", "sentences": {"present": "Er überlegt, was er tun soll.", "past": "Sie überlegte lange.", "future": "Ich werde es mir überlegen.", "usage1": "Ich muss das überlegen.", "usage2": "Hast du das gut überlegt?", "usage3": "Überleg dir das gut."}},
    {"german": "überprüfen", "article": "", "english": "to check, to verify, to review", "wordType": "verb", "plural": "", "verbForms": {"present": "überprüft", "past": "überprüfte", "participle": "überprüft"}, "theme": "work", "sentences": {"present": "Er überprüft die Daten.", "past": "Sie überprüfte alle Dokumente.", "future": "Bitte überprüfen Sie das.", "usage1": "Das muss überprüft werden.", "usage2": "Wer überprüft das?", "usage3": "Haben Sie das überprüft?"}},
    {"german": "überqueren", "article": "", "english": "to cross (street, bridge)", "wordType": "verb", "plural": "", "verbForms": {"present": "überquert", "past": "überquerte", "participle": "überquert"}, "theme": "travel", "sentences": {"present": "Sie überquert die Straße.", "past": "Er überquerte die Brücke.", "future": "Wir werden den Fluss überqueren.", "usage1": "Überquere die Straße vorsichtig.", "usage2": "Die Grenze wurde überquert.", "usage3": "Wo kann man die Straße überqueren?"}},
    {"german": "übersetzen", "article": "", "english": "to translate", "wordType": "verb", "plural": "", "verbForms": {"present": "übersetzt", "past": "übersetzte", "participle": "übersetzt"}, "theme": "language_exam", "sentences": {"present": "Er übersetzt den Text.", "past": "Sie übersetzte das Buch.", "future": "Ich werde das übersetzen.", "usage1": "Kannst du das übersetzen?", "usage2": "Das wurde ins Englische übersetzt.", "usage3": "Wie übersetzt man das?"}},
    {"german": "widersprechen", "article": "", "english": "to contradict, to object", "wordType": "verb", "plural": "", "verbForms": {"present": "widerspricht", "past": "widersprach", "participle": "widersprochen"}, "theme": "relationships", "sentences": {"present": "Er widerspricht mir.", "past": "Sie widersprach dem Chef.", "future": "Ich werde dem widersprechen.", "usage1": "Darf ich widersprechen?", "usage2": "Niemand hat widersprochen.", "usage3": "Das widerspricht der Regel."}},
    {"german": "zwingen", "article": "", "english": "to force, to compel", "wordType": "verb", "plural": "", "verbForms": {"present": "zwingt", "past": "zwang", "participle": "gezwungen"}, "theme": "society", "sentences": {"present": "Er zwingt sie dazu.", "past": "Sie wurde gezwungen.", "future": "Niemand wird dich zwingen.", "usage1": "Ich werde nicht gezwungen.", "usage2": "Er zwang sie zu schweigen.", "usage3": "Das zwingt mich zu reagieren."}},
]

with open(VOCAB_PATH, encoding='utf-8') as f:
    vocab = json.load(f)

our_lower = {w['german'].lower() for w in vocab}
max_idx = max(int(w['id'].split('_')[-1]) for w in vocab if w['id'].split('_')[-1].isdigit())
idx = max_idx + 1

added, skipped = [], []
for w in NEW_WORDS:
    if w['german'].lower() in our_lower:
        skipped.append(w['german'])
    else:
        raw = re.sub(r'[äöüÄÖÜß ]', lambda m: {
            'ä':'ae','ö':'oe','ü':'ue','Ä':'ae','Ö':'oe','Ü':'ue','ß':'ss',' ':'_'
        }[m.group()], w['german'].lower())
        raw = re.sub(r'[^a-z0-9_]', '', raw)
        w['id'] = f"{raw}_{idx}"
        idx += 1
        added.append(w)
        our_lower.add(w['german'].lower())

vocab.extend(added)
with open(VOCAB_PATH, 'w', encoding='utf-8') as f:
    json.dump(vocab, f, ensure_ascii=False, indent=2)

print(f"Added: {len(added)}, Skipped: {len(skipped)}, Total: {len(vocab)}")
if skipped:
    print(f"Skipped: {skipped}")
