import json, re, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

VOCAB_PATH = "assets/data/vocabulary.json"

NEW_WORDS = [
    # --- Adjectives ---
    {"german": "aktiv", "article": "", "english": "active", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "health", "sentences": {"present": "Er ist sehr aktiv.", "past": "Sie war früher aktiver.", "future": "Bleib aktiv!", "usage1": "Ein aktiver Lebensstil ist gesund.", "usage2": "Das Kind ist sehr aktiv.", "usage3": "Sie führt ein aktives Leben."}},
    {"german": "aktuell", "article": "", "english": "current, up-to-date", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Das ist eine aktuelle Nachricht.", "past": "Die Informationen waren nicht aktuell.", "future": "Halte dich aktuell.", "usage1": "Das ist nicht mehr aktuell.", "usage2": "Aktuelle Neuigkeiten findest du online.", "usage3": "Ist das noch aktuell?"}},
    {"german": "ähnlich", "article": "", "english": "similar", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Die beiden sind sich sehr ähnlich.", "past": "Das war eine ähnliche Situation.", "future": "Das wird ähnlich sein.", "usage1": "Das sieht ähnlich aus.", "usage2": "Ihre Meinungen sind ähnlich.", "usage3": "Etwas Ähnliches ist passiert."}},
    {"german": "angenehm", "article": "", "english": "pleasant, agreeable", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Das Wetter ist heute angenehm.", "past": "Der Abend war sehr angenehm.", "future": "Es wird angenehm sein.", "usage1": "Angenehm, Sie kennenzulernen!", "usage2": "Das ist sehr angenehm.", "usage3": "Eine angenehme Atmosphäre."}},
    {"german": "ängstlich", "article": "", "english": "anxious, fearful", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "health", "sentences": {"present": "Das Kind ist ängstlich.", "past": "Sie war sehr ängstlich.", "future": "Sei nicht so ängstlich.", "usage1": "Er wirkt ängstlich.", "usage2": "Warum bist du so ängstlich?", "usage3": "Sie ist von Natur aus ängstlich."}},
    {"german": "bereit", "article": "", "english": "ready, prepared", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Bist du bereit?", "past": "Er war bereit abzureisen.", "future": "Ich werde bereit sein.", "usage1": "Alles ist bereit.", "usage2": "Ich bin nicht bereit.", "usage3": "Wir sind bereit anzufangen."}},
    {"german": "böse", "article": "", "english": "angry; evil, bad", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "relationships", "sentences": {"present": "Er ist böse auf mich.", "past": "Sie war wirklich böse.", "future": "Sei nicht böse!", "usage1": "Bist du böse mit mir?", "usage2": "Das war eine böse Überraschung.", "usage3": "Er macht immer böse Witze."}},
    {"german": "deutlich", "article": "", "english": "clear, distinct, obvious", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Das ist deutlich besser.", "past": "Der Unterschied war deutlich.", "future": "Das wird deutlicher.", "usage1": "Bitte sprechen Sie deutlicher.", "usage2": "Das zeigt sich deutlich.", "usage3": "Eine deutliche Verbesserung."}},
    {"german": "dick", "article": "", "english": "thick; fat", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Das Buch ist sehr dick.", "past": "Die Mauer war dick.", "future": "Das wird zu dick sein.", "usage1": "Ein dickes Stück Brot.", "usage2": "Der Pulli ist dick und warm.", "usage3": "Die Wände sind dick."}},
    {"german": "dünn", "article": "", "english": "thin, slim", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Das Papier ist sehr dünn.", "past": "Die Suppe war zu dünn.", "future": "Das wird zu dünn sein.", "usage1": "Sie ist sehr dünn.", "usage2": "Ein dünnes Hemd.", "usage3": "Die Schicht ist dünn."}},
    {"german": "ehrlich", "article": "", "english": "honest, sincere", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "relationships", "sentences": {"present": "Er ist sehr ehrlich.", "past": "Sie war immer ehrlich.", "future": "Sei ehrlich mit mir.", "usage1": "Ehrlich gesagt, weiß ich es nicht.", "usage2": "Eine ehrliche Antwort.", "usage3": "Er ist ein ehrlicher Mensch."}},
    {"german": "einsam", "article": "", "english": "lonely", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "relationships", "sentences": {"present": "Sie fühlt sich einsam.", "past": "Er war lange einsam.", "future": "Du wirst dich nicht mehr einsam fühlen.", "usage1": "Ich fühle mich einsam.", "usage2": "Einsamkeit ist schwer.", "usage3": "Er ist sehr einsam."}},
    {"german": "faul", "article": "", "english": "lazy; rotten", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Er ist heute faul.", "past": "Sie war nie faul.", "future": "Sei nicht so faul!", "usage1": "Das Obst ist faul.", "usage2": "Ein fauler Schüler.", "usage3": "Ich fühle mich faul heute."}},
    {"german": "fertig", "article": "", "english": "ready, done, finished", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Ich bin fertig.", "past": "Das Essen war fertig.", "future": "Wann wirst du fertig sein?", "usage1": "Bist du fertig?", "usage2": "Alles ist fertig.", "usage3": "Ich bin fast fertig."}},
    {"german": "fleißig", "article": "", "english": "hardworking, diligent", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "education", "sentences": {"present": "Sie ist sehr fleißig.", "past": "Er war immer fleißig.", "future": "Sei fleißig!", "usage1": "Ein fleißiger Schüler.", "usage2": "Sie arbeitet fleißig.", "usage3": "Fleißige Menschen haben Erfolg."}},
    {"german": "flexibel", "article": "", "english": "flexible", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "work", "sentences": {"present": "Er ist sehr flexibel.", "past": "Die Arbeitszeiten waren flexibel.", "future": "Wir müssen flexibel sein.", "usage1": "Ich bin zeitlich flexibel.", "usage2": "Flexible Arbeitszeiten sind beliebt.", "usage3": "Das System ist nicht flexibel."}},
    {"german": "froh", "article": "", "english": "glad, happy", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "relationships", "sentences": {"present": "Ich bin froh, dass du hier bist.", "past": "Sie war froh, als es vorbei war.", "future": "Du wirst froh sein.", "usage1": "Ich bin froh darüber.", "usage2": "Sei froh!", "usage3": "Er ist froh und dankbar."}},
    {"german": "früh", "article": "", "english": "early", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "time_numbers", "sentences": {"present": "Es ist noch früh.", "past": "Er kam zu früh an.", "future": "Wir werden früh aufstehen.", "usage1": "Morgen früh um 7.", "usage2": "Es ist zu früh.", "usage3": "Ich stehe gern früh auf."}},
    {"german": "furchtbar", "article": "", "english": "terrible, awful", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Das ist furchtbar!", "past": "Der Unfall war furchtbar.", "future": "Das wird furchtbar sein.", "usage1": "Das Wetter ist furchtbar.", "usage2": "Ich fühle mich furchtbar.", "usage3": "Das war furchtbar laut."}},
    {"german": "gemütlich", "article": "", "english": "cosy, comfortable; leisurely", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Die Wohnung ist sehr gemütlich.", "past": "Der Abend war gemütlich.", "future": "Es wird gemütlich sein.", "usage1": "Mach es dir gemütlich.", "usage2": "Ein gemütliches Café.", "usage3": "Wir hatten einen gemütlichen Abend."}},
    {"german": "genau", "article": "", "english": "exact, precise; exactly", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Das ist genau richtig.", "past": "Er war sehr genau.", "future": "Gib mir die genaue Adresse.", "usage1": "Genau!", "usage2": "Wie genau ist das?", "usage3": "Das weiß ich nicht genau."}},
    {"german": "hübsch", "article": "", "english": "pretty, nice-looking", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Sie ist sehr hübsch.", "past": "Das Kleid war hübsch.", "future": "Du wirst hübsch aussehen.", "usage1": "Ein hübsches Mädchen.", "usage2": "Das sieht hübsch aus.", "usage3": "Wie hübsch!"}},
    {"german": "kaputt", "article": "", "english": "broken, damaged", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Das Handy ist kaputt.", "past": "Der Computer war kaputt.", "future": "Das wird kaputt gehen.", "usage1": "Mein Fahrrad ist kaputt.", "usage2": "Ich bin total kaputt (exhausted).", "usage3": "Das ist kaputt."}},
    {"german": "krank", "article": "", "english": "sick, ill", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "health", "sentences": {"present": "Er ist krank.", "past": "Sie war letzte Woche krank.", "future": "Werde nicht krank!", "usage1": "Ich bin krank.", "usage2": "Er ist schwer krank.", "usage3": "Bist du noch krank?"}},
    {"german": "langweilig", "article": "", "english": "boring", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Der Film ist langweilig.", "past": "Das Buch war langweilig.", "future": "Das wird langweilig sein.", "usage1": "Ich finde das langweilig.", "usage2": "Ein langweiliger Tag.", "usage3": "Das ist so langweilig!"}},
    {"german": "lustig", "article": "", "english": "funny, amusing", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "culture", "sentences": {"present": "Er ist sehr lustig.", "past": "Der Witz war lustig.", "future": "Das wird lustig sein.", "usage1": "Das ist lustig!", "usage2": "Ein lustiger Film.", "usage3": "Sie macht immer lustige Witze."}},
    {"german": "modern", "article": "", "english": "modern", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "technology", "sentences": {"present": "Das Büro ist sehr modern.", "past": "Das Design war modern.", "future": "Das wird modern sein.", "usage1": "Ein modernes Apartment.", "usage2": "Sie trägt moderne Kleidung.", "usage3": "Das ist nicht mehr modern."}},
    {"german": "müde", "article": "", "english": "tired", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "health", "sentences": {"present": "Ich bin sehr müde.", "past": "Er war nach der Arbeit müde.", "future": "Du wirst müde sein.", "usage1": "Ich bin so müde.", "usage2": "Das Kind ist schon müde.", "usage3": "Warum bist du so müde?"}},
    {"german": "mutig", "article": "", "english": "brave, courageous", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Er ist sehr mutig.", "past": "Sie war mutig in der Krise.", "future": "Sei mutig!", "usage1": "Das war mutig.", "usage2": "Ein mutiger Mensch.", "usage3": "Sei mutig und sag die Wahrheit."}},
    {"german": "nass", "article": "", "english": "wet", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Meine Schuhe sind nass.", "past": "Er war völlig nass.", "future": "Du wirst nass werden.", "usage1": "Ich bin nass geworden.", "usage2": "Das Gras ist nass.", "usage3": "Pass auf, das ist nass!"}},
    {"german": "niedrig", "article": "", "english": "low", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Die Decke ist niedrig.", "past": "Die Preise waren niedrig.", "future": "Die Temperatur wird niedrig sein.", "usage1": "Ein niedriges Einkommen.", "usage2": "Die Brücke ist zu niedrig.", "usage3": "Das Risiko ist niedrig."}},
    {"german": "offen", "article": "", "english": "open; honest", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "relationships", "sentences": {"present": "Das Fenster ist offen.", "past": "Der Laden war noch offen.", "future": "Die Stelle ist offen.", "usage1": "Sei offen zu mir.", "usage2": "Offen gesagt, gefällt es mir nicht.", "usage3": "Die Tür ist offen."}},
    {"german": "öffentlich", "article": "", "english": "public", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "society", "sentences": {"present": "Das ist ein öffentliches Gebäude.", "past": "Die Sitzung war öffentlich.", "future": "Das wird öffentlich bekannt.", "usage1": "Öffentliche Verkehrsmittel.", "usage2": "Das ist öffentliches Eigentum.", "usage3": "Auf öffentlichem Platz."}},
    {"german": "ordentlich", "article": "", "english": "tidy, neat; proper", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Sein Zimmer ist ordentlich.", "past": "Sie war immer ordentlich.", "future": "Halte das ordentlich.", "usage1": "Sei bitte ordentlich.", "usage2": "Eine ordentliche Mahlzeit.", "usage3": "Das sieht ordentlich aus."}},
    {"german": "peinlich", "article": "", "english": "embarrassing", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "relationships", "sentences": {"present": "Das ist so peinlich!", "past": "Die Situation war peinlich.", "future": "Das wird peinlich sein.", "usage1": "Ich finde das peinlich.", "usage2": "Ein peinlicher Moment.", "usage3": "Das ist mir sehr peinlich."}},
    {"german": "populär", "article": "", "english": "popular", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "culture", "sentences": {"present": "Der Sänger ist sehr populär.", "past": "Das war früher populär.", "future": "Das wird populär werden.", "usage1": "Ein populäres Lied.", "usage2": "Das ist sehr populär.", "usage3": "Warum ist das so populär?"}},
    {"german": "praktisch", "article": "", "english": "practical; handy", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Das ist sehr praktisch.", "past": "Die Lösung war praktisch.", "future": "Das wird praktisch sein.", "usage1": "Ein praktischer Rucksack.", "usage2": "Das ist praktisch!", "usage3": "Hast du eine praktische Lösung?"}},
    {"german": "privat", "article": "", "english": "private", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Das ist meine Privatangelegenheit.", "past": "Das Gespräch war privat.", "future": "Das bleibt privat.", "usage1": "Das ist privat.", "usage2": "Ein privates Gespräch.", "usage3": "Bitte nicht weitersagen, das ist privat."}},
    {"german": "ruhig", "article": "", "english": "quiet, calm", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Die Stadt ist ruhig.", "past": "Der Abend war ruhig.", "future": "Es wird ruhig sein.", "usage1": "Sei ruhig!", "usage2": "Ein ruhiges Zimmer.", "usage3": "Er ist ein ruhiger Mensch."}},
    {"german": "satt", "article": "", "english": "full (after eating), satiated", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "food", "sentences": {"present": "Ich bin satt.", "past": "Er war nach dem Essen satt.", "future": "Du wirst satt werden.", "usage1": "Bist du satt?", "usage2": "Ich bin schon satt.", "usage3": "Nach dem Mittagessen bin ich immer satt."}},
    {"german": "sauber", "article": "", "english": "clean", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Die Küche ist sauber.", "past": "Das Zimmer war sauber.", "future": "Halte das sauber.", "usage1": "Mach das sauber!", "usage2": "Sauberes Wasser ist wichtig.", "usage3": "Ist das sauber?"}},
    {"german": "sauer", "article": "", "english": "sour; angry (colloquial)", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "food", "sentences": {"present": "Die Zitrone ist sauer.", "past": "Der Wein war zu sauer.", "future": "Das wird sauer sein.", "usage1": "Er ist sauer auf mich.", "usage2": "Das schmeckt sauer.", "usage3": "Saure Gurken mag ich gern."}},
    {"german": "scharf", "article": "", "english": "sharp; spicy (food)", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "food", "sentences": {"present": "Das Essen ist zu scharf.", "past": "Das Messer war scharf.", "future": "Pass auf, das ist scharf.", "usage1": "Ich esse gern scharf.", "usage2": "Ein scharfes Messer.", "usage3": "Ist das scharf?"}},
    {"german": "schlank", "article": "", "english": "slim, slender", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "health", "sentences": {"present": "Sie ist sehr schlank.", "past": "Er war früher schlanker.", "future": "Sie will schlank bleiben.", "usage1": "Eine schlanke Figur.", "usage2": "Er sieht schlank aus.", "usage3": "Wie bleibt man schlank?"}},
    {"german": "schwach", "article": "", "english": "weak", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "health", "sentences": {"present": "Er ist nach der Krankheit schwach.", "past": "Das Team war schwach.", "future": "Ich fühle mich schwach.", "usage1": "Das ist seine schwache Seite.", "usage2": "Ein schwaches Signal.", "usage3": "Er ist körperlich schwach."}},
    {"german": "schwanger", "article": "", "english": "pregnant", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "health", "sentences": {"present": "Sie ist schwanger.", "past": "Sie war im dritten Monat schwanger.", "future": "Sie wird bald schwanger sein.", "usage1": "Ich bin schwanger.", "usage2": "Eine schwangere Frau.", "usage3": "Wie lange sind Sie schon schwanger?"}},
    {"german": "schwierig", "article": "", "english": "difficult, hard", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "education", "sentences": {"present": "Die Aufgabe ist schwierig.", "past": "Das Gespräch war schwierig.", "future": "Das wird schwierig sein.", "usage1": "Das ist zu schwierig.", "usage2": "Eine schwierige Frage.", "usage3": "Warum ist das so schwierig?"}},
    {"german": "selten", "article": "", "english": "rare, seldom", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Das ist selten.", "past": "Solche Fehler waren selten.", "future": "Das wird selten vorkommen.", "usage1": "Er kommt selten zu Besuch.", "usage2": "Ein seltenes Tier.", "usage3": "Das passiert nur selten."}},
    {"german": "sinnvoll", "article": "", "english": "meaningful, sensible, useful", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "work", "sentences": {"present": "Das ist eine sinnvolle Idee.", "past": "Das war eine sinnvolle Entscheidung.", "future": "Das wird sinnvoll sein.", "usage1": "Ist das sinnvoll?", "usage2": "Eine sinnvolle Maßnahme.", "usage3": "Das macht keinen sinnvollen Sinn."}},
    {"german": "spannend", "article": "", "english": "exciting, thrilling", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "culture", "sentences": {"present": "Der Film ist spannend.", "past": "Das Spiel war sehr spannend.", "future": "Das wird spannend!", "usage1": "Wie spannend!", "usage2": "Ein spannendes Buch.", "usage3": "Das Leben ist spannend."}},
    {"german": "stark", "article": "", "english": "strong; heavy (rain etc.)", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "health", "sentences": {"present": "Er ist körperlich stark.", "past": "Der Wind war stark.", "future": "Das Signal wird stärker.", "usage1": "Ein starker Mann.", "usage2": "Starker Regen.", "usage3": "Sie ist innerlich stark."}},
    {"german": "stolz", "article": "", "english": "proud", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "relationships", "sentences": {"present": "Ich bin stolz auf dich.", "past": "Sie war stolz auf ihren Sohn.", "future": "Du wirst stolz sein.", "usage1": "Er ist sehr stolz.", "usage2": "Sei stolz auf dich.", "usage3": "Ich bin so stolz auf mein Kind."}},
    {"german": "süß", "article": "", "english": "sweet; cute", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "food", "sentences": {"present": "Das Eis ist sehr süß.", "past": "Das Dessert war süß.", "future": "Das wird zu süß sein.", "usage1": "Wie süß!", "usage2": "Ein süßes Baby.", "usage3": "Ich mag keine zu süßen Sachen."}},
    {"german": "sympathisch", "article": "", "english": "likeable, nice, pleasant", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "relationships", "sentences": {"present": "Er ist sehr sympathisch.", "past": "Sie wirkte sympathisch.", "future": "Du wirst ihr sympathisch sein.", "usage1": "Er ist ein sympathischer Mensch.", "usage2": "Das finde ich sympathisch.", "usage3": "Sie macht einen sympathischen Eindruck."}},
    {"german": "tolerant", "article": "", "english": "tolerant", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "society", "sentences": {"present": "Er ist sehr tolerant.", "past": "Die Gesellschaft war weniger tolerant.", "future": "Wir müssen toleranter werden.", "usage1": "Sei tolerant!", "usage2": "Eine tolerante Gesellschaft.", "usage3": "Er ist gegenüber anderen tolerant."}},
    {"german": "toll", "article": "", "english": "great, fantastic", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Das ist toll!", "past": "Das war toll.", "future": "Das wird toll sein.", "usage1": "Du siehst toll aus.", "usage2": "Ein tolles Erlebnis.", "usage3": "Das finde ich toll."}},
    {"german": "trocken", "article": "", "english": "dry", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Die Wäsche ist trocken.", "past": "Das Wetter war trocken.", "future": "Es wird trocken bleiben.", "usage1": "Halte das trocken.", "usage2": "Ein trockener Wein.", "usage3": "Meine Haut ist trocken."}},
    {"german": "typisch", "article": "", "english": "typical", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "culture", "sentences": {"present": "Das ist typisch deutsch.", "past": "Das war typisch für ihn.", "future": "Das wird typisch sein.", "usage1": "Typisch!", "usage2": "Ein typisches Gericht.", "usage3": "Das ist typisch für die Region."}},
    {"german": "wahr", "article": "", "english": "true, real", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Das ist wahr.", "past": "Die Geschichte war wahr.", "future": "Das wird sich als wahr herausstellen.", "usage1": "Ist das wahr?", "usage2": "Eine wahre Geschichte.", "usage3": "Das kann nicht wahr sein."}},
    {"german": "weich", "article": "", "english": "soft", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Das Kissen ist weich.", "past": "Das Brot war weich.", "future": "Das wird weich sein.", "usage1": "Ein weiches Bett.", "usage2": "Weich gekochtes Ei.", "usage3": "Das Leder ist weich."}},
    {"german": "wichtig", "article": "", "english": "important", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Das ist sehr wichtig.", "past": "Das war ein wichtiger Termin.", "future": "Das wird wichtig sein.", "usage1": "Bitte, das ist wichtig!", "usage2": "Wichtige Informationen.", "usage3": "Was ist dir wichtig?"}},
    {"german": "wütend", "article": "", "english": "furious, angry", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "relationships", "sentences": {"present": "Er ist wütend auf mich.", "past": "Sie war sehr wütend.", "future": "Das wird dich wütend machen.", "usage1": "Ich bin so wütend!", "usage2": "Ein wütender Kunde.", "usage3": "Warum bist du wütend?"}},
    {"german": "zufrieden", "article": "", "english": "satisfied, content", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "relationships", "sentences": {"present": "Ich bin zufrieden.", "past": "Sie war zufrieden mit der Arbeit.", "future": "Bist du zufrieden?", "usage1": "Sind Sie zufrieden?", "usage2": "Ein zufriedener Kunde.", "usage3": "Ich bin sehr zufrieden damit."}},
    {"german": "zuverlässig", "article": "", "english": "reliable, dependable", "wordType": "adjective", "plural": "", "verbForms": {}, "theme": "work", "sentences": {"present": "Er ist sehr zuverlässig.", "past": "Sie war immer zuverlässig.", "future": "Du musst zuverlässig sein.", "usage1": "Ein zuverlässiger Mitarbeiter.", "usage2": "Das System ist zuverlässig.", "usage3": "Bist du zuverlässig?"}},

    # --- Adverbs ---
    {"german": "allerdings", "article": "", "english": "however; admittedly; indeed", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Das stimmt allerdings nicht.", "past": "Er kam, allerdings zu spät.", "future": "Das ist allerdings möglich.", "usage1": "Allerdings habe ich keine Zeit.", "usage2": "Das war allerdings falsch.", "usage3": "Allerdings muss ich zugeben..."}},
    {"german": "bereits", "article": "", "english": "already", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "time_numbers", "sentences": {"present": "Er ist bereits dort.", "past": "Sie hatte bereits gegessen.", "future": "Ich werde bereits fertig sein.", "usage1": "Bist du bereits fertig?", "usage2": "Das ist bereits bekannt.", "usage3": "Er hat das bereits gemacht."}},
    {"german": "bisher", "article": "", "english": "so far, up to now", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "time_numbers", "sentences": {"present": "Bisher hat er alles richtig gemacht.", "past": "Bisher war alles gut.", "future": "Was haben wir bisher gelernt?", "usage1": "Bisher keine Probleme.", "usage2": "Das ist das Beste, was ich bisher gesehen habe.", "usage3": "Bisher hat das geklappt."}},
    {"german": "damals", "article": "", "english": "back then, at that time", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "time_numbers", "sentences": {"present": "Das war damals anders.", "past": "Damals lebten wir in Hamburg.", "future": "Damals konnte man das nicht wissen.", "usage1": "Damals war alles einfacher.", "usage2": "Ich war damals jung.", "usage3": "Damals gab es kein Internet."}},
    {"german": "deshalb", "article": "", "english": "therefore, that's why", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Es regnet, deshalb bleibe ich zu Hause.", "past": "Er war krank, deshalb kam er nicht.", "future": "Das ist wichtig, deshalb musst du aufpassen.", "usage1": "Deshalb habe ich Nein gesagt.", "usage2": "Ich habe keine Zeit, deshalb muss ich absagen.", "usage3": "Deshalb ist es so schwierig."}},
    {"german": "eigentlich", "article": "", "english": "actually, in fact; originally", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Eigentlich wollte ich früher kommen.", "past": "Das war eigentlich nicht geplant.", "future": "Was wolltest du eigentlich sagen?", "usage1": "Eigentlich mag ich das nicht.", "usage2": "Was ist eigentlich passiert?", "usage3": "Ich wollte eigentlich absagen."}},
    {"german": "fast", "article": "", "english": "almost, nearly", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Ich bin fast fertig.", "past": "Er hat fast gewonnen.", "future": "Das wird fast unmöglich sein.", "usage1": "Fast jeder kennt das.", "usage2": "Das ist fast zu teuer.", "usage3": "Wir sind fast da."}},
    {"german": "kaum", "article": "", "english": "hardly, scarcely, barely", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Er kann kaum schlafen.", "past": "Sie hatte kaum Zeit.", "future": "Ich werde kaum Zeit haben.", "usage1": "Das ist kaum möglich.", "usage2": "Ich kenne ihn kaum.", "usage3": "Kaum zu glauben!"}},
    {"german": "manchmal", "article": "", "english": "sometimes", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "time_numbers", "sentences": {"present": "Manchmal esse ich Pizza.", "past": "Manchmal war er traurig.", "future": "Manchmal werde ich daran denken.", "usage1": "Ich gehe manchmal joggen.", "usage2": "Manchmal ist das Leben schwer.", "usage3": "Das passiert manchmal."}},
    {"german": "meistens", "article": "", "english": "mostly, usually, most of the time", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "time_numbers", "sentences": {"present": "Ich trinke meistens Kaffee.", "past": "Er kam meistens zu spät.", "future": "Das wird meistens so sein.", "usage1": "Meistens bin ich pünktlich.", "usage2": "Sie isst meistens gesund.", "usage3": "Das klappt meistens gut."}},
    {"german": "natürlich", "article": "", "english": "of course, naturally", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Natürlich komme ich.", "past": "Das war natürlich so geplant.", "future": "Natürlich werde ich helfen.", "usage1": "Natürlich!", "usage2": "Das ist natürlich falsch.", "usage3": "Natürlich kannst du kommen."}},
    {"german": "nie", "article": "", "english": "never", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "time_numbers", "sentences": {"present": "Er lügt nie.", "past": "Sie hat das nie gemacht.", "future": "Das werde ich nie vergessen.", "usage1": "Nie wieder!", "usage2": "Ich war noch nie in Japan.", "usage3": "Das passiert mir nie."}},
    {"german": "normalerweise", "article": "", "english": "normally, usually", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "daily_life", "sentences": {"present": "Normalerweise schlafe ich um 10.", "past": "Normalerweise war er pünktlich.", "future": "Normalerweise werde ich kommen.", "usage1": "Normalerweise mag ich das.", "usage2": "Was machst du normalerweise?", "usage3": "Normalerweise klappt das."}},
    {"german": "oft", "article": "", "english": "often", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "time_numbers", "sentences": {"present": "Sie kommt oft zu spät.", "past": "Er hat oft Fehler gemacht.", "future": "Ich werde dich oft besuchen.", "usage1": "Wie oft gehst du ins Gym?", "usage2": "Das passiert oft.", "usage3": "Ich gehe oft spazieren."}},
    {"german": "schon", "article": "", "english": "already; quite; indeed", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "time_numbers", "sentences": {"present": "Ich bin schon fertig.", "past": "Er war schon weg.", "future": "Das wird schon klappen.", "usage1": "Bist du schon da?", "usage2": "Ich kenne das schon.", "usage3": "Das klappt schon."}},
    {"german": "sofort", "article": "", "english": "immediately, right away", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "time_numbers", "sentences": {"present": "Ich komme sofort.", "past": "Sie kam sofort.", "future": "Das werde ich sofort erledigen.", "usage1": "Ich bin sofort da.", "usage2": "Ruf sofort an!", "usage3": "Das muss sofort gemacht werden."}},
    {"german": "sogar", "article": "", "english": "even", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Er kann sogar Russisch.", "past": "Sie hat sogar gewonnen.", "future": "Das wird sogar einfacher sein.", "usage1": "Das ist sogar möglich.", "usage2": "Er hat sogar gelacht.", "usage3": "Sogar ich wusste das."}},
    {"german": "trotzdem", "article": "", "english": "nevertheless, still, anyway", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Es regnet, trotzdem gehe ich raus.", "past": "Er war müde, trotzdem arbeitete er.", "future": "Ich werde trotzdem kommen.", "usage1": "Das ist falsch, trotzdem mache ich es.", "usage2": "Trotzdem danke!", "usage3": "Er hat trotzdem gewonnen."}},
    {"german": "überall", "article": "", "english": "everywhere", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "other", "sentences": {"present": "Das sieht man überall.", "past": "Er reiste überall hin.", "future": "Das wird überall bekannt sein.", "usage1": "Überall gibt es Probleme.", "usage2": "Ich suche es überall.", "usage3": "Das Internet ist überall verfügbar."}},
    {"german": "vielleicht", "article": "", "english": "perhaps, maybe", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Vielleicht komme ich morgen.", "past": "Vielleicht hat er Recht.", "future": "Das wird vielleicht klappen.", "usage1": "Vielleicht!", "usage2": "Komm vielleicht später.", "usage3": "Das ist vielleicht möglich."}},
    {"german": "wahrscheinlich", "article": "", "english": "probably, likely", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Er kommt wahrscheinlich morgen.", "past": "Das war wahrscheinlich ein Fehler.", "future": "Das wird wahrscheinlich schwierig sein.", "usage1": "Wahrscheinlich ja.", "usage2": "Das stimmt wahrscheinlich.", "usage3": "Er ist wahrscheinlich krank."}},
    {"german": "wirklich", "article": "", "english": "really, truly", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Das ist wirklich schön.", "past": "Das war wirklich toll.", "future": "Das wird wirklich helfen.", "usage1": "Ich meine das wirklich.", "usage2": "Wirklich?!", "usage3": "Das hat wirklich geholfen."}},
    {"german": "ziemlich", "article": "", "english": "quite, fairly, rather", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Das ist ziemlich schwer.", "past": "Das war ziemlich gut.", "future": "Das wird ziemlich teuer.", "usage1": "Das ist ziemlich interessant.", "usage2": "Er kommt ziemlich oft.", "usage3": "Das kostet ziemlich viel."}},
    {"german": "außerdem", "article": "", "english": "besides, moreover, furthermore", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Außerdem ist er krank.", "past": "Er war müde. Außerdem hatte er Hunger.", "future": "Außerdem werde ich das prüfen.", "usage1": "Außerdem bin ich gegen diese Idee.", "usage2": "Das ist teuer. Außerdem...", "usage3": "Außerdem gibt es noch mehr Gründe."}},
    {"german": "gestern", "article": "", "english": "yesterday", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "time_numbers", "sentences": {"present": "Was hast du gestern gemacht?", "past": "Gestern war ich im Kino.", "future": "Was war gestern?", "usage1": "Gestern Abend.", "usage2": "Das passierte gestern.", "usage3": "Ich habe gestern geschlafen."}},
    {"german": "morgen", "article": "", "english": "tomorrow; morning", "wordType": "adverb", "plural": "", "verbForms": {}, "theme": "time_numbers", "sentences": {"present": "Morgen komme ich.", "past": "Morgen früh war er da.", "future": "Ich werde morgen arbeiten.", "usage1": "Bis morgen!", "usage2": "Was machst du morgen?", "usage3": "Morgen ist Montag."}},

    # --- Conjunctions ---
    {"german": "als", "article": "", "english": "when (past); than (comparison)", "wordType": "conjunction", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Er ist größer als sie.", "past": "Als ich jung war, spielte ich Fußball.", "future": "Das ist leichter als gedacht.", "usage1": "Als ich ankam, war es schon spät.", "usage2": "Besser als nichts.", "usage3": "Als Kind mochte ich das."}},
    {"german": "also", "article": "", "english": "so, therefore, well then", "wordType": "conjunction", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Also, was machen wir jetzt?", "past": "Er kam also doch.", "future": "Also, ich werde dabei helfen.", "usage1": "Also gut.", "usage2": "Also, fangen wir an.", "usage3": "Er war krank, also blieb er zu Hause."}},
    {"german": "bevor", "article": "", "english": "before (conjunction)", "wordType": "conjunction", "plural": "", "verbForms": {}, "theme": "time_numbers", "sentences": {"present": "Bevor du gehst, sag mir Bescheid.", "past": "Bevor es regnete, waren wir draußen.", "future": "Bevor wir anfangen, müssen wir planen.", "usage1": "Bevor ich vergesse...", "usage2": "Erledige das, bevor du schläfst.", "usage3": "Bevor es zu spät ist."}},
    {"german": "bis", "article": "", "english": "until, by (time)", "wordType": "conjunction", "plural": "", "verbForms": {}, "theme": "time_numbers", "sentences": {"present": "Ich warte, bis du kommst.", "past": "Er arbeitete bis er müde war.", "future": "Wir warten, bis es aufhört zu regnen.", "usage1": "Bis bald!", "usage2": "Bis Freitag muss das fertig sein.", "usage3": "Ich arbeite bis 18 Uhr."}},
    {"german": "damit", "article": "", "english": "so that, in order to", "wordType": "conjunction", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Ich lerne, damit ich die Prüfung bestehe.", "past": "Er übte, damit er besser wird.", "future": "Ich werde üben, damit ich gewinne.", "usage1": "Damit das klappt, müssen wir arbeiten.", "usage2": "Er rief an, damit sie weiß, dass er kommt.", "usage3": "Damit du es weißt."}},
    {"german": "falls", "article": "", "english": "if, in case", "wordType": "conjunction", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Falls du Fragen hast, ruf an.", "past": "Falls er kommt, sage ich Bescheid.", "future": "Falls es regnet, bleiben wir zu Hause.", "usage1": "Falls nötig, helfe ich.", "usage2": "Falls er absagt, ändert sich der Plan.", "usage3": "Falls du Zeit hast, komm vorbei."}},
    {"german": "ob", "article": "", "english": "whether, if (indirect question)", "wordType": "conjunction", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Ich weiß nicht, ob er kommt.", "past": "Sie fragte, ob er krank sei.", "future": "Ich bin nicht sicher, ob das klappt.", "usage1": "Weißt du, ob er da ist?", "usage2": "Ich frage mich, ob das stimmt.", "usage3": "Egal ob ja oder nein."}},
    {"german": "obwohl", "article": "", "english": "although, even though", "wordType": "conjunction", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Obwohl es regnet, gehe ich spazieren.", "past": "Obwohl er müde war, arbeitete er weiter.", "future": "Obwohl es schwer sein wird, werde ich es versuchen.", "usage1": "Obwohl ich keine Lust habe...", "usage2": "Er lachte, obwohl es nicht lustig war.", "usage3": "Obwohl wir spät dran waren."}},
    {"german": "seit", "article": "", "english": "since, for (duration)", "wordType": "conjunction", "plural": "", "verbForms": {}, "theme": "time_numbers", "sentences": {"present": "Seit ich hier bin, geht es mir gut.", "past": "Seit er gegangen war, war es ruhig.", "future": "Seit wann bist du hier?", "usage1": "Ich wohne seit 5 Jahren hier.", "usage2": "Seit gestern bin ich krank.", "usage3": "Seit wann kennst du ihn?"}},
    {"german": "sobald", "article": "", "english": "as soon as", "wordType": "conjunction", "plural": "", "verbForms": {}, "theme": "time_numbers", "sentences": {"present": "Sobald er ankommt, rufe ich an.", "past": "Sobald sie fertig war, ging sie.", "future": "Sobald ich fertig bin, komme ich.", "usage1": "Sobald möglich.", "usage2": "Ruf mich an, sobald du da bist.", "usage3": "Sobald das Ergebnis da ist."}},
    {"german": "sodass", "article": "", "english": "so that (result)", "wordType": "conjunction", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Es ist so laut, sodass ich nichts höre.", "past": "Er arbeitete viel, sodass er müde wurde.", "future": "Das ist klar, sodass jeder versteht.", "usage1": "Er fuhr schnell, sodass er pünktlich ankam.", "usage2": "Es regnete stark, sodass das Spiel abgesagt wurde.", "usage3": "Sodass wir das wissen."}},
    {"german": "solange", "article": "", "english": "as long as, while", "wordType": "conjunction", "plural": "", "verbForms": {}, "theme": "time_numbers", "sentences": {"present": "Solange es geht, bleibe ich.", "past": "Solange er hier war, half er.", "future": "Solange du willst.", "usage1": "Solange du hier bist, passe ich auf.", "usage2": "Solange es keine Probleme gibt.", "usage3": "Mach das, solange du kannst."}},
    {"german": "sondern", "article": "", "english": "but rather, but instead (after negative)", "wordType": "conjunction", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Das ist nicht falsch, sondern richtig.", "past": "Er kam nicht am Montag, sondern am Dienstag.", "future": "Nicht er, sondern sie wird kommen.", "usage1": "Nicht nur..., sondern auch...", "usage2": "Das ist nicht schwer, sondern einfach.", "usage3": "Er kommt nicht, sondern schreibt."}},
    {"german": "während", "article": "", "english": "while, during (conjunction)", "wordType": "conjunction", "plural": "", "verbForms": {}, "theme": "time_numbers", "sentences": {"present": "Während sie kocht, lese ich.", "past": "Während er schlief, arbeitete sie.", "future": "Während du das machst, warte ich.", "usage1": "Während des Essens schweigen.", "usage2": "Während der Arbeit.", "usage3": "Während ich schlief, regnete es."}},
    {"german": "weil", "article": "", "english": "because", "wordType": "conjunction", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Ich komme nicht, weil ich krank bin.", "past": "Er blieb zu Hause, weil es regnete.", "future": "Ich lerne viel, weil ich erfolgreich sein will.", "usage1": "Warum? Weil ich muss!", "usage2": "Weil es so ist.", "usage3": "Ich mag ihn, weil er nett ist."}},
    {"german": "wenn", "article": "", "english": "if; when (repeated/future)", "wordType": "conjunction", "plural": "", "verbForms": {}, "theme": "language_exam", "sentences": {"present": "Wenn es regnet, bleibe ich zu Hause.", "past": "Wenn ich Zeit hatte, las ich.", "future": "Wenn du kommst, werde ich da sein.", "usage1": "Wenn möglich, bitte früher.", "usage2": "Wenn du willst.", "usage3": "Wenn ich das gewusst hätte!"}},
]

with open(VOCAB_PATH, encoding='utf-8') as f:
    vocab = json.load(f)

our_lower = {w['german'].lower() for w in vocab}
max_idx = max(int(w['id'].split('_')[-1]) for w in vocab if w['id'].split('_')[-1].isdigit())
idx = max_idx + 1

added, skipped = [], []
for w in NEW_WORDS:
    if w['german'].lower() in our_lower:
        skipped.append(w['german'])
    else:
        raw = re.sub(r'[äöüÄÖÜß ]', lambda m: {
            'ä':'ae','ö':'oe','ü':'ue','Ä':'ae','Ö':'oe','Ü':'ue','ß':'ss',' ':'_'
        }[m.group()], w['german'].lower())
        raw = re.sub(r'[^a-z0-9_]', '', raw)
        w['id'] = f"{raw}_{idx}"
        idx += 1
        added.append(w)
        our_lower.add(w['german'].lower())

vocab.extend(added)
with open(VOCAB_PATH, 'w', encoding='utf-8') as f:
    json.dump(vocab, f, ensure_ascii=False, indent=2)

print(f"Added: {len(added)}, Skipped: {len(skipped)}, Total: {len(vocab)}")
if skipped:
    print(f"Skipped: {skipped}")
