// AUTO-GENERATED by scripts/fetch_images.py — do not edit manually
// Maps word IDs to bundled noun images for React Native
// Stub: run scripts/fetch_images.py to populate
const imageMap: Record<string, any> = {};
export default imageMap;
