"""
add_noun_forms.py
Adds nounForm field to every verb in vocabulary.json.
nounForm is the most natural/common noun derived from the verb, with article.
Set to null where no clean noun form exists (modals, auxiliaries, etc.)
"""
import json, pathlib

VOCAB_PATH = pathlib.Path(__file__).parent.parent / "assets/data/vocabulary.json"

# german verb → noun form (with article) or None
NOUN_FORMS: dict[str, str | None] = {
    # A
    "abbiegen":        "die Abbiegung",
    "abgeben":         "die Abgabe",
    "abheben":         "die Abhebung",
    "abholen":         "die Abholung",
    "ablehnen":        "die Ablehnung",
    "abmachen":        "die Abmachung",
    "abnehmen":        "die Abnahme",
    "absagen":         "die Absage",
    "abschließen":     "der Abschluss",
    "abschreiben":     "die Abschrift",
    "abstimmen":       "die Abstimmung",
    "abwaschen":       "das Abwaschen",
    "achten":          "die Achtung",
    "ändern":          "die Änderung",
    "anerkennen":      "die Anerkennung",
    "anfassen":        None,
    "angeben":         "die Angabe",
    "anbieten":        "das Angebot",
    "ankreuzen":       None,
    "ankündigen":      "die Ankündigung",
    "anmachen":        None,
    "anmelden":        "die Anmeldung",
    "annehmen":        "die Annahme",
    "anpassen":        "die Anpassung",
    "anrufen":         "der Anruf",
    "anschalten":      None,
    "anschaffen":      "die Anschaffung",
    "anschließen":     "der Anschluss",
    "anschnallen":     None,
    "ansehen":         "das Ansehen",
    "ansprechen":      "die Ansprache",
    "atmen":           "die Atmung",
    "auffordern":      "die Aufforderung",
    "aufladen":        "die Aufladung",
    "aufmachen":       "die Aufmachung",
    "aufnehmen":       "die Aufnahme",
    "aufpassen":       None,
    "aufräumen":       "das Aufräumen",
    "aufregen":        "die Aufregung",
    "aufstehen":       "das Aufstehen",
    "aufwachen":       "das Aufwachen",
    "anhaben":         None,
    "ausgeben":        "die Ausgabe",
    "ausgehen":        "der Ausgang",
    "ausdrucken":      "der Ausdruck",
    "ausmachen":       None,
    "ausrichten":      "die Ausrichtung",
    "ausschalten":     None,
    "ausschließen":    "der Ausschluss",
    "aussehen":        "das Aussehen",
    "aussprechen":     "die Aussprache",
    "ausstellen":      "die Ausstellung",
    "auswählen":       "die Auswahl",
    "ausziehen":       "der Auszug",
    "ärgern":          "der Ärger",
    # B
    "backen":          "das Backen",
    "baden":           "das Baden",
    "bauen":           "der Bau",
    "bedienen":        "die Bedienung",
    "beeinflussen":    "der Einfluss",
    "sich beeilen":    "die Eile",
    "beenden":         "die Beendigung",
    "begegnen":        "die Begegnung",
    "begründen":       "die Begründung",
    "begrüßen":        "die Begrüßung",
    "behalten":        None,
    "behandeln":       "die Behandlung",
    "behaupten":       "die Behauptung",
    "beißen":          "der Biss",
    "beobachten":      "die Beobachtung",
    "beraten":         "die Beratung",
    "beschädigen":     "die Beschädigung",
    "beschäftigen":    "die Beschäftigung",
    "beschließen":     "der Beschluss",
    "beschränken":     "die Beschränkung",
    "beschreiben":     "die Beschreibung",
    "besitzen":        "der Besitz",
    "besprechen":      "die Besprechung",
    "bestätigen":      "die Bestätigung",
    "betrügen":        "der Betrug",
    "bewerben":        "die Bewerbung",
    "bewohnen":        None,
    "bieten":          "das Gebot",
    "bitten":          "die Bitte",
    "bleiben":         "das Bleiben",
    "blitzen":         "der Blitz",
    "blühen":          "die Blüte",
    "bluten":          "die Blutung",
    "braten":          "der Braten",
    "brechen":         "der Bruch",
    "brennen":         "der Brand",
    "bringen":         "das Bringen",
    "buchen":          "die Buchung",
    # D
    "danken":          "der Dank",
    "dauern":          "die Dauer",
    "denken":          "der Gedanke",
    "dienen":          "der Dienst",
    "drehen":          "die Drehung",
    "drucken":         "der Druck",
    "drücken":         "der Druck",
    "dürfen":          None,
    "duzen":           "das Duzen",
    # E
    "sich eignen":     "die Eignung",
    "einbrechen":      "der Einbruch",
    "einfallen":       "der Einfall",
    "einführen":       "die Einführung",
    "sich einigen":    "die Einigung",
    "einladen":        "die Einladung",
    "einnehmen":       "die Einnahme",
    "einrichten":      "die Einrichtung",
    "einschalten":     None,
    "einschlafen":     "der Schlaf",
    "empfangen":       "der Empfang",
    "enden":           "das Ende",
    "entscheiden":     "die Entscheidung",
    "entwickeln":      "die Entwicklung",
    "erfahren":        "die Erfahrung",
    "erfinden":        "die Erfindung",
    "erfüllen":        "die Erfüllung",
    "erhalten":        "der Erhalt",
    "erhöhen":         "die Erhöhung",
    "sich erkälten":   "die Erkältung",
    "erklären":        "die Erklärung",
    "erleben":         "das Erlebnis",
    "erledigen":       "die Erledigung",
    "erleichtern":     "die Erleichterung",
    "ernähren":        "die Ernährung",
    "erreichen":       "das Erreichen",
    "erschrecken":     "der Schreck",
    "ersetzen":        "der Ersatz",
    "erzeugen":        "die Erzeugung",
    "erziehen":        "die Erziehung",
    "essen":           "das Essen",
    "existieren":      "die Existenz",
    # F
    "fallen":          "der Fall",
    "fangen":          "der Fang",
    "fassen":          "die Fassung",
    "fehlen":          "das Fehlen",
    "feiern":          "die Feier",
    "feststehen":      None,
    "feststellen":     "die Feststellung",
    "finden":          "der Fund",
    "fliegen":         "der Flug",
    "fliehen":         "die Flucht",
    "fließen":         "der Fluss",
    "flüstern":        "das Flüstern",
    "folgen":          "die Folge",
    "fordern":         "die Forderung",
    "fördern":         "die Förderung",
    "fotografieren":   "die Fotografie",
    "fragen":          "die Frage",
    "fressen":         "das Fressen",
    "sich freuen":     "die Freude",
    "frieren":         "der Frost",
    "frühstücken":     "das Frühstück",
    "fühlen":          "das Gefühl",
    "führen":          "die Führung",
    "füttern":         "die Fütterung",
    # G
    "geben":           "die Gabe",
    "gefallen":        "das Gefallen",
    "gehen":           "der Gang",
    "gehören":         None,
    "gelingen":        "das Gelingen",
    "gelten":          "die Geltung",
    "genehmigen":      "die Genehmigung",
    "genießen":        "der Genuss",
    "genügen":         None,
    "gewinnen":        "der Gewinn",
    "glauben":         "der Glaube",
    "gratulieren":     "die Gratulation",
    "greifen":         "der Griff",
    "grillen":         "das Grillen",
    "grüßen":          "der Gruß",
    "gucken":          None,
    # H
    "haben":           None,
    "hageln":          "der Hagel",
    "halten":          "der Halt",
    "hassen":          "der Hass",
    "heben":           "das Heben",
    "heißen":          None,
    "heizen":          "die Heizung",
    "helfen":          "die Hilfe",
    "hinterlassen":    "die Hinterlassenschaft",
    "hoffen":          "die Hoffnung",
    "holen":           None,
    "hören":           "das Gehör",
    "hupen":           "die Hupe",
    "husten":          "der Husten",
    # I
    "informieren":     "die Information",
    "interessieren":   "das Interesse",
    # K
    "kennen":          "die Kenntnis",
    "klagen":          "die Klage",
    "klappen":         None,
    "klären":          "die Klärung",
    "kleben":          "der Kleber",
    "klettern":        "das Klettern",
    "klicken":         "der Klick",
    "klingen":         "der Klang",
    "klopfen":         "das Klopfen",
    "kochen":          "das Kochen",
    "kommen":          "die Ankunft",
    "können":          None,
    "konsumieren":     "der Konsum",
    "kontrollieren":   "die Kontrolle",
    "kosten":          "die Kosten",
    "kriegen":         None,
    "kündigen":        "die Kündigung",
    "küssen":          "der Kuss",
    # L
    "lächeln":         "das Lächeln",
    "lachen":          "das Lachen",
    "landen":          "die Landung",
    "sich langweilen": "die Langeweile",
    "lassen":          None,
    "laufen":          "der Lauf",
    "leben":           "das Leben",
    "legen":           None,
    "leid tun":        "das Leid",
    "leiden":          "das Leiden",
    "leihen":          "die Leihe",
    "leisten":         "die Leistung",
    "leiten":          "die Leitung",
    "lernen":          "das Lernen",
    "lesen":           "das Lesen",
    "lieben":          "die Liebe",
    "liefern":         "die Lieferung",
    "loben":           "das Lob",
    "sich lohnen":     None,
    "löschen":         "die Löschung",
    "lösen":           "die Lösung",
    "lügen":           "die Lüge",
    # M
    "machen":          None,
    "malen":           "die Malerei",
    "meinen":          "die Meinung",
    "melden":          "die Meldung",
    "merken":          None,
    "messen":          "die Messung",
    "mieten":          "die Miete",
    "mischen":         "die Mischung",
    "mitteilen":       "die Mitteilung",
    "möchten":         None,
    "mögen":           None,
    "müssen":          None,
    # N
    "nachdenken":      "die Überlegung",
    "nachschauen":     None,
    "sich nähern":     "die Annäherung",
    "nähen":           "das Nähen",
    "nehmen":          None,
    "nennen":          "die Nennung",
    "nutzen":          "die Nutzung",
    "nützen":          "der Nutzen",
    # O
    "öffnen":          "die Öffnung",
    "ordnen":          "die Ordnung",
    "organisieren":    "die Organisation",
    # P
    "packen":          "die Packung",
    "parken":          "das Parken",
    "passen":          None,
    "pflegen":         "die Pflege",
    "planen":          "die Planung",
    "probieren":       "die Probe",
    "produzieren":     "die Produktion",
    "protestieren":    "der Protest",
    "prüfen":          "die Prüfung",
    "putzen":          "das Putzen",
    # R
    "raten":           "der Rat",
    "rauchen":         "der Rauch",
    "reden":           "die Rede",
    "regeln":          "die Regelung",
    "reichen":         None,
    "reinigen":        "die Reinigung",
    "reisen":          "die Reise",
    "reiten":          "der Ritt",
    "rennen":          "das Rennen",
    "retten":          "die Rettung",
    "riechen":         "der Geruch",
    "rufen":           "der Ruf",
    # S
    "sagen":           "die Aussage",
    "schaffen":        "die Schaffung",
    "schauen":         None,
    "scheinen":        "der Schein",
    "schicken":        "die Sendung",
    "schieben":        "der Schub",
    "schießen":        "der Schuss",
    "schlafen":        "der Schlaf",
    "schlagen":        "der Schlag",
    "schmecken":       "der Geschmack",
    "schreien":        "der Schrei",
    "schützen":        "der Schutz",
    "schwimmen":       "das Schwimmen",
    "sein":            None,
    "sehen":           "das Sehen",
    "sichern":         "die Sicherung",
    "siegen":          "der Sieg",
    "sinken":          "das Sinken",
    "singen":          "der Gesang",
    "sollen":          None,
    "sorgen":          "die Sorge",
    "sparen":          "die Ersparnis",
    "speichern":       "die Speicherung",
    "spielen":         "das Spiel",
    "sprechen":        "das Gespräch",
    "springen":        "der Sprung",
    "spülen":          "das Spülen",
    "spüren":          "das Spüren",
    "stammen":         "die Abstammung",
    "starten":         "der Start",
    "stattfinden":     "die Veranstaltung",
    "staubsaugen":     "das Staubsaugen",
    "stechen":         "der Stich",
    "stecken":         None,
    "stehlen":         "der Diebstahl",
    "steigen":         "der Anstieg",
    "stellen":         "die Stellung",
    "sterben":         "der Tod",
    "stimmen":         "die Abstimmung",
    "stinken":         "der Gestank",
    "stoppen":         "der Stopp",
    "stören":          "die Störung",
    "streiken":        "der Streik",
    "stürzen":         "der Sturz",
    "suchen":          "die Suche",
    # T
    "tanken":          "das Tanken",
    "tanzen":          "der Tanz",
    "tauschen":        "der Tausch",
    "teilnehmen":      "die Teilnahme",
    "telefonieren":    "das Telefonieren",
    "teilen":          "die Teilung",
    "testen":          "der Test",
    "tippen":          None,
    "tragen":          "das Tragen",
    "träumen":         "der Traum",
    "treffen":         "das Treffen",
    "treiben":         "das Treiben",
    "trennen":         "die Trennung",
    "trinken":         "das Trinken",
    "trocknen":        "das Trocknen",
    "tun":             None,
    # Ü
    "überlegen":       "die Überlegung",
    "übernachten":     "die Übernachtung",
    "übernehmen":      "die Übernahme",
    "überprüfen":      "die Überprüfung",
    "überqueren":      "die Überquerung",
    "überraschen":     "die Überraschung",
    "übersetzen":      "die Übersetzung",
    "überweisen":      "die Überweisung",
    "umsteigen":       "der Umstieg",
    "umtauschen":      "der Umtausch",
    "umziehen":        "der Umzug",
    "unterbrechen":    "die Unterbrechung",
    "unterrichten":    "der Unterricht",
    "unterschreiben":  "die Unterschrift",
    "unterstützen":    "die Unterstützung",
    "untersuchen":     "die Untersuchung",
    # V
    "verbessern":      "die Verbesserung",
    "verbinden":       "die Verbindung",
    "verbrauchen":     "der Verbrauch",
    "verdienen":       "der Verdienst",
    "vereinbaren":     "die Vereinbarung",
    "vergessen":       "das Vergessen",
    "vergleichen":     "der Vergleich",
    "sich vergnügen":  "das Vergnügen",
    "vergrößern":      "die Vergrößerung",
    "verhindern":      "die Verhinderung",
    "verlängern":      "die Verlängerung",
    "verlassen":       "das Verlassen",
    "verlieren":       "der Verlust",
    "verletzen":       "die Verletzung",
    "vermeiden":       "die Vermeidung",
    "vermissen":       "das Vermissen",
    "verpassen":       "das Verpassen",
    "verraten":        "der Verrat",
    "verschreiben":    "die Verschreibung",
    "verschwinden":    "das Verschwinden",
    "versichern":      "die Versicherung",
    "versprechen":     "das Versprechen",
    "versuchen":       "der Versuch",
    "vertreten":       "die Vertretung",
    "verursachen":     "die Verursachung",
    "verwechseln":     "die Verwechslung",
    "vorschlagen":     "der Vorschlag",
    "vorstellen":      "die Vorstellung",
    "vorkommen":       "das Vorkommen",
    # W
    "wachsen":         "das Wachstum",
    "wählen":          "die Wahl",
    "wandern":         "die Wanderung",
    "warnen":          "die Warnung",
    "warten":          "das Warten",
    "wecken":          "das Wecken",
    "wechseln":        "der Wechsel",
    "sich weigern":    "die Weigerung",
    "wehtun":          "der Schmerz",
    "weinen":          "das Weinen",
    "werden":          None,
    "werfen":          "der Wurf",
    "wetten":          "die Wette",
    "widersprechen":   "der Widerspruch",
    "wiederholen":     "die Wiederholung",
    "wiegen":          "das Gewicht",
    "winken":          "das Winken",
    "wirken":          "die Wirkung",
    "wissen":          "das Wissen",
    "wohnen":          "die Wohnung",
    "wollen":          None,
    "wünschen":        "der Wunsch",
    # Z
    "zahlen":          "die Zahlung",
    "zählen":          "die Zahl",
    "zeichnen":        "die Zeichnung",
    "zeigen":          "das Zeigen",
    "zelten":          "das Zelten",
    "zerstören":       "die Zerstörung",
    "zubereiten":      "die Zubereitung",
    "zugehen":         None,
    "zuhören":         "das Zuhören",
    "zunehmen":        "die Zunahme",
    "zurechtkommen":   None,
    "zusagen":         "die Zusage",
    "zu sein":         None,
    "zuschauen":       "das Zuschauen",
    "zustimmen":       "die Zustimmung",
    "zwingen":         "der Zwang",
}

def main():
    with open(VOCAB_PATH, encoding="utf-8") as f:
        words = json.load(f)

    matched = 0
    unmatched_verbs = []

    for word in words:
        if word["wordType"] != "verb":
            # add null for non-verbs so the field is always present
            word["nounForm"] = None
            continue

        german = word["german"]
        noun_form = NOUN_FORMS.get(german)

        if noun_form is not None:
            matched += 1
        elif german not in NOUN_FORMS:
            unmatched_verbs.append(german)

        word["nounForm"] = noun_form

    with open(VOCAB_PATH, "w", encoding="utf-8") as f:
        json.dump(words, f, ensure_ascii=False, indent=2)

    total_verbs = sum(1 for w in words if w["wordType"] == "verb")
    with_form = sum(1 for w in words if w["wordType"] == "verb" and w.get("nounForm"))
    print(f"Total verbs: {total_verbs}")
    print(f"With noun form: {with_form} ({with_form/total_verbs*100:.1f}%)")
    print(f"Without noun form: {total_verbs - with_form}")
    if unmatched_verbs:
        print(f"\nVerbs NOT in dictionary (need manual review):")
        for v in unmatched_verbs:
            print(f"  {v}")

if __name__ == "__main__":
    main()
