#!/usr/bin/env python3
"""
Fetch low-resolution Wikipedia thumbnail images for German nouns.
Saves JPEGs to assets/images/nouns/<word_id>.jpg
Generates assets/data/imageMap.ts with static require() calls for React Native.
Updates assets/data/vocabulary.json with 'image' field.

Usage: python scripts/fetch_images.py
Run from the repo root directory.
"""

import json
import time
import sys
from pathlib import Path

import requests

VOCAB_PATH = Path("assets/data/vocabulary.json")
IMAGES_DIR = Path("assets/images/nouns")
IMAGE_MAP_PATH = Path("assets/data/imageMap.ts")
HEADERS = {"User-Agent": "VelocitrainerApp/2.0 (educational; contact: github.com/ansarijibran-dev/deutsch-b1)"}
THUMB_SIZE = 200  # pixels wide


def search_wikipedia_image(german_word: str) -> str | None:
    """Returns the thumbnail URL for the first Wikipedia article matching the German word."""
    api = "https://en.wikipedia.org/w/api.php"
    params = {
        "action": "query",
        "titles": german_word,
        "prop": "pageimages",
        "format": "json",
        "pithumbsize": THUMB_SIZE,
        "pilicense": "any",
    }
    try:
        resp = requests.get(api, params=params, headers=HEADERS, timeout=10)
        resp.raise_for_status()
        pages = resp.json().get("query", {}).get("pages", {})
        for page in pages.values():
            if page.get("pageid", -1) != -1 and "thumbnail" in page:
                return page["thumbnail"]["source"]
    except Exception:
        pass
    return None


def download_image(url: str, dest: Path) -> bool:
    try:
        resp = requests.get(url, headers=HEADERS, timeout=15)
        resp.raise_for_status()
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(resp.content)
        return True
    except Exception as e:
        print(f"  Download failed: {e}", file=sys.stderr)
        return False


def generate_image_map(image_ids: list[str]) -> None:
    """Generate assets/data/imageMap.ts with static require() calls."""
    lines = [
        "// AUTO-GENERATED by scripts/fetch_images.py — do not edit manually",
        "// Maps word IDs to bundled noun images for React Native",
        "const imageMap: Record<string, any> = {",
    ]
    for word_id in sorted(image_ids):
        lines.append(f"  '{word_id}': require('../images/nouns/{word_id}.jpg'),")
    lines.append("};")
    lines.append("export default imageMap;")
    IMAGE_MAP_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    IMAGES_DIR.mkdir(parents=True, exist_ok=True)

    print(f"Loading {VOCAB_PATH}...")
    with open(VOCAB_PATH, encoding="utf-8") as f:
        vocab = json.load(f)

    nouns = [w for w in vocab if w.get("wordType") == "noun"]
    print(f"Found {len(nouns)} nouns to process.")

    success_ids = []
    failed = []

    # Collect already-downloaded ids to allow re-runs
    already_done = {w["id"] for w in vocab if w.get("image")}

    for i, word in enumerate(nouns):
        word_id = word["id"]
        german = word["german"]
        # Strip article if present in the german field
        bare = german.split()[-1] if " " in german else german

        if word_id in already_done:
            print(f"  [{i+1}/{len(nouns)}] {german} — already downloaded, skipping")
            success_ids.append(word_id)
            continue

        dest = IMAGES_DIR / f"{word_id}.jpg"
        print(f"  [{i+1}/{len(nouns)}] {german}...", end=" ", flush=True)

        img_url = search_wikipedia_image(bare)
        if img_url is None:
            print("no image found")
            failed.append(german)
            time.sleep(0.3)
            continue

        ok = download_image(img_url, dest)
        if not ok:
            failed.append(german)
            time.sleep(0.3)
            continue

        # Update vocabulary entry
        for w in vocab:
            if w["id"] == word_id:
                w["image"] = f"assets/images/nouns/{word_id}.jpg"
                break

        success_ids.append(word_id)
        print("OK")
        time.sleep(0.3)

    print(f"\nDone: {len(success_ids)} images, {len(failed)} failed.")
    if failed:
        print("Failed nouns (no image will be shown):")
        for n in failed:
            print(f"  {n}")

    print(f"Generating {IMAGE_MAP_PATH}...")
    generate_image_map(success_ids)

    print(f"Saving {VOCAB_PATH}...")
    with open(VOCAB_PATH, "w", encoding="utf-8") as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)
    print("All done.")


if __name__ == "__main__":
    main()
